import { boatActivityKinds } from '../domain/boat-activity'
import type { BoatActivityKind } from '../domain/boat-activity'

export type BoatActivityTranslationKey =
  | `boatActivity_${BoatActivityKind}`
  | 'boatActivity_open'
  | 'boatActivity_unavailable'
const labels: Record<string, string> = {
  en: 'Media added|Media updated|Media removed|Document added|Document updated|Document removed|Asset added|Asset updated|Asset removed|Assets connected|Assets disconnected|Network connection added|Network connection removed|Purchase added|Purchase removed|Contact added|Contact updated|Contact removed|Member added|Member updated|Member removed|Share added|Share updated|Share removed|Open document|File no longer available',
  sv: 'Media tillagt|Media uppdaterat|Media borttaget|Dokument tillagt|Dokument uppdaterat|Dokument borttaget|Utrustning tillagd|Utrustning uppdaterad|Utrustning borttagen|Utrustning ansluten|Utrustning frånkopplad|Nätverksanslutning tillagd|Nätverksanslutning borttagen|Inköp tillagt|Inköp borttaget|Kontakt tillagd|Kontakt uppdaterad|Kontakt borttagen|Medlem tillagd|Medlem uppdaterad|Medlem borttagen|Andel tillagd|Andel uppdaterad|Andel borttagen|Öppna dokument|Filen är inte längre tillgänglig',
  vi: 'Đã thêm phương tiện|Đã cập nhật phương tiện|Đã xóa phương tiện|Đã thêm tài liệu|Đã cập nhật tài liệu|Đã xóa tài liệu|Đã thêm thiết bị|Đã cập nhật thiết bị|Đã xóa thiết bị|Đã kết nối thiết bị|Đã ngắt kết nối thiết bị|Đã thêm kết nối mạng|Đã xóa kết nối mạng|Đã thêm giao dịch mua|Đã xóa giao dịch mua|Đã thêm liên hệ|Đã cập nhật liên hệ|Đã xóa liên hệ|Đã thêm thành viên|Đã cập nhật thành viên|Đã xóa thành viên|Đã thêm phần sở hữu|Đã cập nhật phần sở hữu|Đã xóa phần sở hữu|Mở tài liệu|Tệp không còn khả dụng',
  es: 'Contenido multimedia añadido|Contenido multimedia actualizado|Contenido multimedia eliminado|Documento añadido|Documento actualizado|Documento eliminado|Equipo añadido|Equipo actualizado|Equipo eliminado|Equipos conectados|Equipos desconectados|Conexión de red añadida|Conexión de red eliminada|Compra añadida|Compra eliminada|Contacto añadido|Contacto actualizado|Contacto eliminado|Miembro añadido|Miembro actualizado|Miembro eliminado|Participación añadida|Participación actualizada|Participación eliminada|Abrir documento|El archivo ya no está disponible',
  fr: 'Média ajouté|Média mis à jour|Média supprimé|Document ajouté|Document mis à jour|Document supprimé|Équipement ajouté|Équipement mis à jour|Équipement supprimé|Équipements connectés|Équipements déconnectés|Connexion réseau ajoutée|Connexion réseau supprimée|Achat ajouté|Achat supprimé|Contact ajouté|Contact mis à jour|Contact supprimé|Membre ajouté|Membre mis à jour|Membre supprimé|Part ajoutée|Part mise à jour|Part supprimée|Ouvrir le document|Fichier indisponible',
  nl: 'Media toegevoegd|Media bijgewerkt|Media verwijderd|Document toegevoegd|Document bijgewerkt|Document verwijderd|Uitrusting toegevoegd|Uitrusting bijgewerkt|Uitrusting verwijderd|Uitrusting verbonden|Uitrusting losgekoppeld|Netwerkverbinding toegevoegd|Netwerkverbinding verwijderd|Aankoop toegevoegd|Aankoop verwijderd|Contact toegevoegd|Contact bijgewerkt|Contact verwijderd|Lid toegevoegd|Lid bijgewerkt|Lid verwijderd|Aandeel toegevoegd|Aandeel bijgewerkt|Aandeel verwijderd|Document openen|Bestand niet meer beschikbaar',
  de: 'Medien hinzugefügt|Medien aktualisiert|Medien entfernt|Dokument hinzugefügt|Dokument aktualisiert|Dokument entfernt|Ausrüstung hinzugefügt|Ausrüstung aktualisiert|Ausrüstung entfernt|Geräte verbunden|Geräte getrennt|Netzwerkverbindung hinzugefügt|Netzwerkverbindung entfernt|Kauf hinzugefügt|Kauf entfernt|Kontakt hinzugefügt|Kontakt aktualisiert|Kontakt entfernt|Mitglied hinzugefügt|Mitglied aktualisiert|Mitglied entfernt|Anteil hinzugefügt|Anteil aktualisiert|Anteil entfernt|Dokument öffnen|Datei nicht mehr verfügbar',
  pt: 'Média adicionada|Média atualizada|Média removida|Documento adicionado|Documento atualizado|Documento removido|Equipamento adicionado|Equipamento atualizado|Equipamento removido|Equipamentos ligados|Equipamentos desligados|Ligação de rede adicionada|Ligação de rede removida|Compra adicionada|Compra removida|Contacto adicionado|Contacto atualizado|Contacto removido|Membro adicionado|Membro atualizado|Membro removido|Quota adicionada|Quota atualizada|Quota removida|Abrir documento|Ficheiro indisponível',
  el: 'Προστέθηκαν πολυμέσα|Ενημερώθηκαν πολυμέσα|Αφαιρέθηκαν πολυμέσα|Προστέθηκε έγγραφο|Ενημερώθηκε έγγραφο|Αφαιρέθηκε έγγραφο|Προστέθηκε εξοπλισμός|Ενημερώθηκε εξοπλισμός|Αφαιρέθηκε εξοπλισμός|Συνδέθηκε εξοπλισμός|Αποσυνδέθηκε εξοπλισμός|Προστέθηκε σύνδεση δικτύου|Αφαιρέθηκε σύνδεση δικτύου|Προστέθηκε αγορά|Αφαιρέθηκε αγορά|Προστέθηκε επαφή|Ενημερώθηκε επαφή|Αφαιρέθηκε επαφή|Προστέθηκε μέλος|Ενημερώθηκε μέλος|Αφαιρέθηκε μέλος|Προστέθηκε μερίδιο|Ενημερώθηκε μερίδιο|Αφαιρέθηκε μερίδιο|Άνοιγμα εγγράφου|Το αρχείο δεν είναι πλέον διαθέσιμο',
  tr: 'Medya eklendi|Medya güncellendi|Medya kaldırıldı|Belge eklendi|Belge güncellendi|Belge kaldırıldı|Ekipman eklendi|Ekipman güncellendi|Ekipman kaldırıldı|Ekipman bağlandı|Ekipman bağlantısı kesildi|Ağ bağlantısı eklendi|Ağ bağlantısı kaldırıldı|Satın alma eklendi|Satın alma kaldırıldı|Kişi eklendi|Kişi güncellendi|Kişi kaldırıldı|Üye eklendi|Üye güncellendi|Üye kaldırıldı|Pay eklendi|Pay güncellendi|Pay kaldırıldı|Belgeyi aç|Dosya artık kullanılamıyor',
  zh: '已添加媒体|已更新媒体|已移除媒体|已添加文档|已更新文档|已移除文档|已添加设备|已更新设备|已移除设备|已连接设备|已断开设备|已添加网络连接|已移除网络连接|已添加采购|已移除采购|已添加联系人|已更新联系人|已移除联系人|已添加成员|已更新成员|已移除成员|已添加份额|已更新份额|已移除份额|打开文档|文件已不可用',
  yue: '已新增媒體|已更新媒體|已移除媒體|已新增文件|已更新文件|已移除文件|已新增設備|已更新設備|已移除設備|已連接設備|已中斷設備連接|已新增網絡連接|已移除網絡連接|已新增採購|已移除採購|已新增聯絡人|已更新聯絡人|已移除聯絡人|已新增成員|已更新成員|已移除成員|已新增份額|已更新份額|已移除份額|開啟文件|檔案已無法使用',
  ja: 'メディアを追加|メディアを更新|メディアを削除|書類を追加|書類を更新|書類を削除|設備を追加|設備を更新|設備を削除|設備を接続|設備の接続を解除|ネットワーク接続を追加|ネットワーク接続を削除|購入を追加|購入を削除|連絡先を追加|連絡先を更新|連絡先を削除|メンバーを追加|メンバーを更新|メンバーを削除|持分を追加|持分を更新|持分を削除|書類を開く|ファイルは利用できなくなりました',
  ko: '미디어 추가됨|미디어 업데이트됨|미디어 삭제됨|문서 추가됨|문서 업데이트됨|문서 삭제됨|장비 추가됨|장비 업데이트됨|장비 삭제됨|장비 연결됨|장비 연결 해제됨|네트워크 연결 추가됨|네트워크 연결 삭제됨|구매 추가됨|구매 삭제됨|연락처 추가됨|연락처 업데이트됨|연락처 삭제됨|멤버 추가됨|멤버 업데이트됨|멤버 삭제됨|지분 추가됨|지분 업데이트됨|지분 삭제됨|문서 열기|파일을 더 이상 사용할 수 없습니다',
  fi: 'Media lisätty|Media päivitetty|Media poistettu|Asiakirja lisätty|Asiakirja päivitetty|Asiakirja poistettu|Varuste lisätty|Varuste päivitetty|Varuste poistettu|Varusteet yhdistetty|Varusteiden yhteys katkaistu|Verkkoyhteys lisätty|Verkkoyhteys poistettu|Osto lisätty|Osto poistettu|Yhteystieto lisätty|Yhteystieto päivitetty|Yhteystieto poistettu|Jäsen lisätty|Jäsen päivitetty|Jäsen poistettu|Osuus lisätty|Osuus päivitetty|Osuus poistettu|Avaa asiakirja|Tiedosto ei ole enää saatavilla',
  da: 'Medie tilføjet|Medie opdateret|Medie fjernet|Dokument tilføjet|Dokument opdateret|Dokument fjernet|Udstyr tilføjet|Udstyr opdateret|Udstyr fjernet|Udstyr forbundet|Udstyr frakoblet|Netværksforbindelse tilføjet|Netværksforbindelse fjernet|Køb tilføjet|Køb fjernet|Kontakt tilføjet|Kontakt opdateret|Kontakt fjernet|Medlem tilføjet|Medlem opdateret|Medlem fjernet|Andel tilføjet|Andel opdateret|Andel fjernet|Åbn dokument|Filen er ikke længere tilgængelig',
  ar: 'تمت إضافة وسائط|تم تحديث الوسائط|تمت إزالة الوسائط|تمت إضافة مستند|تم تحديث المستند|تمت إزالة المستند|تمت إضافة معدات|تم تحديث المعدات|تمت إزالة المعدات|تم توصيل المعدات|تم فصل المعدات|تمت إضافة اتصال شبكة|تمت إزالة اتصال شبكة|تمت إضافة عملية شراء|تمت إزالة عملية شراء|تمت إضافة جهة اتصال|تم تحديث جهة الاتصال|تمت إزالة جهة اتصال|تمت إضافة عضو|تم تحديث العضو|تمت إزالة عضو|تمت إضافة حصة|تم تحديث الحصة|تمت إزالة حصة|فتح المستند|الملف لم يعد متاحًا',
}
export function boatActivityCopy(
  language: string,
): Record<BoatActivityTranslationKey, string> {
  const keys = [
    ...boatActivityKinds.map((kind) => `boatActivity_${kind}`),
    'boatActivity_open',
    'boatActivity_unavailable',
  ]
  return Object.fromEntries(
    keys.map((key, i) => [key, (labels[language] ?? labels.en).split('|')[i]]),
  ) as Record<BoatActivityTranslationKey, string>
}
