import { describe, expect, it } from 'vitest'
import type { LogEntry, Trip } from '../domain/logbook'
import {
  defaultReplayTripName,
  hasReplayedSourceEntry,
  replayEntryElapsedMs,
  replayPositionAt,
  replaySourceEntries,
  replayTimestamp,
} from './dev-trip-replay'

const trip: Trip = {
  id: 'source',
  boatName: 'Aeolus',
  title: 'Summer passage',
  startedAt: '2026-08-01T10:00:00.000Z',
  completedAt: '2026-08-01T12:00:00.000Z',
  startLatitude: 50,
  startLongitude: 10,
  status: 'COMPLETED',
  createdAt: '2026-08-01T10:00:00.000Z',
  updatedAt: '2026-08-01T12:00:00.000Z',
}

function entry(patch: Partial<LogEntry>): LogEntry {
  return {
    id: 'entry',
    tripId: trip.id,
    type: 'HOURLY_LOG',
    timestamp: trip.startedAt,
    createdAt: trip.startedAt,
    updatedAt: trip.startedAt,
    synced: true,
    deleted: false,
    ...patch,
  }
}

describe('dev trip replay', () => {
  it('uses the source display name for the default name', () => {
    expect(defaultReplayTripName(trip)).toBe('Summer passage replay')
  })

  it('keeps only machine-detectable events in chronological order', () => {
    const entries = [
      entry({ id: 'note', type: 'NOTE', timestamp: '2026-08-01T10:10:00Z' }),
      entry({ id: 'sails', type: 'SAILS_UP', timestamp: '2026-08-01T10:30:00Z' }),
      entry({ id: 'hourly', timestamp: '2026-08-01T11:00:00Z' }),
      entry({ id: 'photo', type: 'PHOTO', timestamp: '2026-08-01T10:20:00Z' }),
    ]

    expect(replaySourceEntries(entries, trip.id).map((item) => item.id)).toEqual([
      'sails',
      'hourly',
    ])
  })

  it('maps source elapsed time onto the new trip clock', () => {
    const sourceEntry = entry({ timestamp: '2026-08-01T11:00:00.000Z' })
    const elapsed = replayEntryElapsedMs(sourceEntry, trip.startedAt)

    expect(elapsed).toBe(60 * 60 * 1000)
    expect(replayTimestamp('2026-08-27T08:00:00.000Z', elapsed)).toBe(
      '2026-08-27T09:00:00.000Z',
    )
  })

  it('interpolates the spoofed position at the original speed', () => {
    const entries = [
      entry({
        timestamp: '2026-08-01T11:00:00.000Z',
        latitude: 52,
        longitude: 14,
        heading: 90,
      }),
    ]

    expect(replayPositionAt(trip, entries, 30 * 60 * 1000)).toEqual({
      latitude: 51,
      longitude: 12,
      accuracy: null,
      heading: 90,
    })
  })

  it('recognizes an emitted event even after the user edits it', () => {
    const targetEntry = entry({
      tripId: 'target',
      data: {
        autoGenerated: true,
        humanEdited: true,
        replaySourceEntryId: 'source-entry',
      },
    })

    expect(hasReplayedSourceEntry([targetEntry], 'source-entry')).toBe(true)
  })
})
