import type { Leg, LogEntry, Trip } from '../domain/logbook'
import type {
  ScalarTrackSample,
  TripTrack,
  TripTrackKind,
} from '../domain/trip-track'
import {
  encodePositionTrackSamples,
  encodeScalarTrackSamples,
  encodingForTrackKind,
} from '../domain/trip-track'
import {
  GPX_MS_TO_KNOTS,
  gpxTrackKindForField,
} from './gpx-field-meta'
import {
  GPX_IMPORT_SOURCE,
  discoverGpxScalarFieldKeys,
  gpxImportBoatName,
  gpxImportSummary,
  gpxImportTripTitle,
  gpxScalarSamplesForField,
  nearestTrackPointTime,
  parseAndMergeGpx,
  parseGpxRaw,
  type GpxImportFile,
  type GpxTrackPoint,
  type GpxTrackSegment,
  type GpxWaypoint,
} from './gpx-import'
import { generateLegColor } from './leg-colors'

function makeId() {
  return crypto.randomUUID()
}

function nowIso() {
  return new Date().toISOString()
}

function toPositionSample(point: GpxTrackPoint) {
  return {
    time: point.time,
    latitude: point.latitude,
    longitude: point.longitude,
    heading: point.heading,
    elevationM: point.elevationM,
  }
}

function buildWaypointEntry(
  tripId: string,
  waypoint: GpxWaypoint,
  timestamp: string,
  createdAtOffsetMs: number,
): LogEntry {
  const createdAt = new Date(Date.now() + createdAtOffsetMs).toISOString()
  const placeName = waypoint.name?.trim()
  return {
    id: makeId(),
    tripId,
    type: 'NOTE',
    timestamp,
    latitude: waypoint.latitude,
    longitude: waypoint.longitude,
    accuracy: null,
    heading: null,
    createdBy: 'captain',
    notes: waypoint.description?.trim() || null,
    data: {
      autoGenerated: true,
      source: GPX_IMPORT_SOURCE,
      gpxWaypoint: true,
      ...(waypoint.symbol ? { gpxSymbol: waypoint.symbol } : {}),
      ...(placeName
        ? {
            place: {
              name: placeName,
              detail: null,
              kind: 'waypoint',
              source: 'osm',
              distanceM: 0,
            },
          }
        : {}),
    },
    weather: null,
    createdAt,
    updatedAt: createdAt,
    synced: false,
    deleted: false,
  }
}

function buildLegsFromGpxSegments(
  tripId: string,
  segments: GpxTrackSegment[],
): Leg[] {
  const now = nowIso()

  return segments.flatMap((segment, sequence) => {
    const firstPoint = segment.points[0]
    const lastPoint = segment.points[segment.points.length - 1]
    if (!firstPoint || !lastPoint) return []

    const trackName = segment.trackName?.trim()
    return [
      {
        id: makeId(),
        tripId,
        sequence,
        title: trackName || null,
        color: generateLegColor(sequence),
        startEventId: null,
        endEventId: null,
        startedAt: firstPoint.time,
        endedAt: lastPoint.time,
        createdAt: now,
        updatedAt: now,
        synced: false,
      },
    ]
  })
}

function buildWaypointEntries(
  tripId: string,
  waypoints: GpxWaypoint[],
  trackPoints: GpxTrackPoint[],
  createdAtOffsetStart: number,
): LogEntry[] {
  return waypoints.flatMap((waypoint, index) => {
    const timestamp =
      waypoint.time ??
      nearestTrackPointTime(trackPoints, waypoint.latitude, waypoint.longitude)
    if (!timestamp) return []

    return [
      buildWaypointEntry(
        tripId,
        waypoint,
        timestamp,
        createdAtOffsetStart + index,
      ),
    ]
  })
}

function buildPositionTripTrack(
  tripId: string,
  legId: string | null,
  points: GpxTrackPoint[],
): TripTrack {
  const samples = points.map(toPositionSample)
  const now = nowIso()
  return {
    id: makeId(),
    tripId,
    legId,
    source: GPX_IMPORT_SOURCE,
    kind: 'position',
    encoding: encodingForTrackKind('position'),
    payload: encodePositionTrackSamples(samples),
    sampleCount: samples.length,
    startedAt: samples[0]!.time,
    endedAt: samples[samples.length - 1]!.time,
    createdAt: now,
    updatedAt: now,
    synced: false,
  }
}

function buildScalarTripTrack(
  tripId: string,
  kind: TripTrackKind,
  samples: ScalarTrackSample[],
): TripTrack {
  const now = nowIso()
  return {
    id: makeId(),
    tripId,
    legId: null,
    source: GPX_IMPORT_SOURCE,
    kind,
    encoding: 'scalar-delta-v1',
    payload: encodeScalarTrackSamples(samples),
    sampleCount: samples.length,
    startedAt: samples[0]!.time,
    endedAt: samples[samples.length - 1]!.time,
    createdAt: now,
    updatedAt: now,
    synced: false,
  }
}

function buildGpxImportScalarTracks(tripId: string, points: GpxTrackPoint[]): TripTrack[] {
  const tracks: TripTrack[] = []

  const sogSamples = gpxScalarSamplesForField(
    points,
    'speed',
    (value) => value * GPX_MS_TO_KNOTS,
  )
  if (sogSamples.length >= 2) {
    tracks.push(buildScalarTripTrack(tripId, 'sog', sogSamples))
  }

  for (const fieldKey of discoverGpxScalarFieldKeys(points)) {
    const samples = gpxScalarSamplesForField(points, fieldKey)
    if (samples.length < 2) continue
    tracks.push(buildScalarTripTrack(tripId, gpxTrackKindForField(fieldKey), samples))
  }

  return tracks
}

function buildPositionTracksForLegs(
  tripId: string,
  segments: GpxTrackSegment[],
  legs: Leg[],
): TripTrack[] {
  const tripLegs = legs
    .filter((leg) => leg.tripId === tripId)
    .sort((a, b) => a.sequence - b.sequence)

  if (tripLegs.length === 0) {
    const allPoints = segments.flatMap((segment) => segment.points)
    if (allPoints.length === 0) return []
    return [buildPositionTripTrack(tripId, null, allPoints)]
  }

  return segments.flatMap((segment, index) => {
    if (segment.points.length === 0) return []
    const leg = tripLegs[index]
    return [buildPositionTripTrack(tripId, leg?.id ?? null, segment.points)]
  })
}

export type GpxImportedTrip = {
  trip: Trip
  entries: LogEntry[]
  tracks: TripTrack[]
  legs: Leg[]
}

function primaryGpxFileName(files: GpxImportFile[]): string | undefined {
  for (const file of files) {
    try {
      if (parseGpxRaw(file.gpxXml).trackSegments.length > 0) {
        return file.fileName
      }
    } catch {
      // try next file
    }
  }
  return files[0]?.fileName
}

export function buildTripFromGpxFiles(
  files: GpxImportFile[],
  options?: {
    boatName?: string
  },
): GpxImportedTrip {
  if (files.length === 0) {
    throw new Error('No GPX files were provided.')
  }

  const parsed = parseAndMergeGpx(files)
  const { startedAt, completedAt } = gpxImportSummary(parsed)
  const boatName = gpxImportBoatName(parsed, primaryGpxFileName(files), options?.boatName)
  const tripId = makeId()
  const now = nowIso()
  const firstPoint = parsed.points[0]!

  const trip: Trip = {
    id: tripId,
    boatName,
    boatId: null,
    boatPhotoUrl: null,
    boatIconId: null,
    registration: null,
    skipper: null,
    skipperKey: null,
    crewMemberIds: null,
    title: gpxImportTripTitle(boatName, startedAt),
    coverKind: 'map',
    coverPhotoDataUrl: null,
    startedAt,
    completedAt,
    startLatitude: firstPoint.latitude,
    startLongitude: firstPoint.longitude,
    startCountry: null,
    status: 'COMPLETED',
    sailsUp: null,
    engineOn: null,
    moored: null,
    anchorDown: null,
    createdAt: now,
    updatedAt: now,
  }

  const legs = buildLegsFromGpxSegments(tripId, parsed.segments)
  const entries = buildWaypointEntries(
    tripId,
    parsed.waypoints,
    parsed.points,
    0,
  )
  const tracks = [
    ...buildPositionTracksForLegs(tripId, parsed.segments, legs),
    ...buildGpxImportScalarTracks(tripId, parsed.points),
  ]

  return { trip, entries, tracks, legs }
}

export function buildTripFromGpx(
  gpxXml: string,
  options?: {
    boatName?: string
    fileName?: string
  },
): GpxImportedTrip {
  return buildTripFromGpxFiles([{ gpxXml, fileName: options?.fileName }], {
    boatName: options?.boatName,
  })
}
