import type { LogEntry, Trip } from '../domain/logbook'
import type { TripTrack } from '../domain/trip-track'
import {
  encodeTrackSamples,
  type TrackSample,
} from '../domain/trip-track'
import {
  GPX_IMPORT_SOURCE,
  gpxImportBoatName,
  gpxImportSummary,
  gpxImportTripTitle,
  parseGpx,
  type GpxTrackPoint,
} from './gpx-import'

function makeId() {
  return crypto.randomUUID()
}

function nowIso() {
  return new Date().toISOString()
}

function toTrackSample(point: GpxTrackPoint): TrackSample {
  return {
    time: point.time,
    latitude: point.latitude,
    longitude: point.longitude,
    heading: point.heading,
    elevationM: point.elevationM,
  }
}

function buildBoundaryEntry(
  tripId: string,
  point: GpxTrackPoint,
  type: 'START_TRIP' | 'END_TRIP',
  createdAtOffsetMs: number,
): LogEntry {
  const createdAt = new Date(Date.now() + createdAtOffsetMs).toISOString()
  return {
    id: makeId(),
    tripId,
    type,
    timestamp: point.time,
    latitude: point.latitude,
    longitude: point.longitude,
    accuracy: null,
    heading: point.heading,
    createdBy: 'captain',
    notes: 'Imported from GPX',
    data: {
      autoGenerated: true,
      source: GPX_IMPORT_SOURCE,
    },
    weather: null,
    createdAt,
    updatedAt: createdAt,
    synced: false,
    deleted: false,
  }
}

function buildTripTrack(tripId: string, samples: TrackSample[]): TripTrack {
  const now = nowIso()
  const payload = encodeTrackSamples(samples)
  return {
    id: makeId(),
    tripId,
    legId: null,
    source: 'gpx-import',
    kind: 'position',
    encoding: 'delta-v1',
    payload,
    sampleCount: samples.length,
    startedAt: samples[0].time,
    endedAt: samples[samples.length - 1].time,
    createdAt: now,
    updatedAt: now,
    synced: false,
  }
}

export type GpxImportedTrip = {
  trip: Trip
  entries: LogEntry[]
  track: TripTrack
}

export function buildTripFromGpx(
  gpxXml: string,
  options?: {
    boatName?: string
    fileName?: string
  },
): GpxImportedTrip {
  const parsed = parseGpx(gpxXml)
  const { startedAt, completedAt } = gpxImportSummary(parsed)
  const boatName = gpxImportBoatName(parsed, options?.fileName, options?.boatName)
  const tripId = makeId()
  const now = nowIso()
  const firstPoint = parsed.points[0]
  const lastPoint = parsed.points[parsed.points.length - 1]
  const samples = parsed.points.map(toTrackSample)

  const trip: Trip = {
    id: tripId,
    boatName,
    boatId: null,
    boatPhotoUrl: null,
    boatIconId: null,
    registration: null,
    skipper: null,
    skipperKey: null,
    crewMemberIds: null,
    title: gpxImportTripTitle(boatName, startedAt),
    coverKind: 'map',
    coverPhotoDataUrl: null,
    startedAt,
    completedAt,
    startLatitude: firstPoint.latitude,
    startLongitude: firstPoint.longitude,
    startCountry: null,
    status: 'COMPLETED',
    sailsUp: null,
    engineOn: null,
    moored: null,
    anchorDown: null,
    createdAt: now,
    updatedAt: now,
  }

  const entries = [
    buildBoundaryEntry(tripId, firstPoint, 'START_TRIP', 0),
    buildBoundaryEntry(tripId, lastPoint, 'END_TRIP', 1),
  ]
  const track = buildTripTrack(tripId, samples)

  return { trip, entries, track }
}
