import { describe, expect, it } from 'vitest'
import type { LogEntry, Trip } from '../domain/logbook'
import {
  buildLiveActivitySnapshot,
  selectLiveActivityTrip,
} from './live-activity'

const trip: Trip = {
  id: 'trip-1',
  boatName: 'North Star',
  title: 'Solent passage',
  startedAt: '2026-08-27T08:00:00.000Z',
  status: 'IN_PROGRESS',
  sailsUp: true,
  engineOn: false,
  moored: false,
  anchorDown: false,
  createdAt: '2026-08-27T07:55:00.000Z',
  updatedAt: '2026-08-27T08:00:00.000Z',
}

function entry(patch: Partial<LogEntry>): LogEntry {
  return {
    id: 'entry-1',
    tripId: trip.id,
    type: 'HOURLY_LOG',
    timestamp: '2026-08-27T09:00:00.000Z',
    createdAt: '2026-08-27T09:00:01.000Z',
    updatedAt: '2026-08-27T09:00:01.000Z',
    synced: true,
    deleted: false,
    ...patch,
  }
}

describe('live activity snapshot', () => {
  it('builds the moving hourly progress window and current place', () => {
    const snapshot = buildLiveActivitySnapshot({
      trip,
      entries: [
        entry({
          data: {
            place: {
              name: 'Cowes',
              detail: 'Isle of Wight',
              kind: 'town',
              source: 'geonames',
              distanceM: 20,
            },
          },
        }),
      ],
      appOrigin: 'https://logmaster.live',
    })

    expect(snapshot.mode).toBe('moving')
    expect(snapshot.locationName).toBe('Cowes')
    expect(snapshot.previousLogAt).toBe('2026-08-27T09:00:00.000Z')
    expect(snapshot.nextLogAt).toBe('2026-08-27T10:00:00.000Z')
  })

  it('prioritizes anchored over moored and marks untouched automatic entries', () => {
    const snapshot = buildLiveActivitySnapshot({
      trip: { ...trip, anchorDown: true, moored: true },
      entries: [
        entry({
          id: 'anchor',
          type: 'ANCHOR_DROPPED',
          timestamp: '2026-08-27T10:00:00.000Z',
          data: { autoGenerated: true },
        }),
      ],
      appOrigin: 'https://logmaster.live',
    })

    expect(snapshot.mode).toBe('stationary')
    expect(snapshot.stationaryKind).toBe('anchored')
    expect(snapshot.stationarySince).toBe('2026-08-27T10:00:00.000Z')
    expect(snapshot.recentEntries[0]?.autoCreatedUnedited).toBe(true)
  })

  it('selects an in-progress trip before the newest planned trip', () => {
    const planned = {
      ...trip,
      id: 'planned',
      status: 'PLANNED' as const,
      updatedAt: '2026-08-27T12:00:00.000Z',
    }
    expect(selectLiveActivityTrip([planned, trip])?.id).toBe(trip.id)
    expect(selectLiveActivityTrip([planned])?.id).toBe(planned.id)
    expect(
      selectLiveActivityTrip([{ ...trip, status: 'COMPLETED' }]),
    ).toBeNull()
  })
})
