import { describe, expect, it } from 'vitest'
import type { LogEntry } from '../domain/logbook'
import {
  collapseColocatedLogEntries,
  logEntryHasHumanInput,
  logEntryMapIconKind,
  logEntryMapMarkerImageId,
  logEntryMapOutline,
} from './log-entry-map-marker'

const entry = (overrides: Partial<LogEntry>): LogEntry =>
  ({
    id: 'entry-1',
    tripId: 'trip-1',
    type: 'NOTE',
    timestamp: '2026-01-01T12:00:00.000Z',
    latitude: 48.1,
    longitude: -123.1,
    deleted: false,
    synced: true,
    notes: null,
    data: null,
    ...overrides,
  }) as LogEntry

describe('logEntryMapIconKind', () => {
  it('maps operational and media types', () => {
    expect(logEntryMapIconKind(entry({ type: 'ANCHOR_DROPPED' }))).toBe(
      'anchor-dropped',
    )
    expect(logEntryMapIconKind(entry({ type: 'ANCHOR_WEIGHED' }))).toBe(
      'anchor-weighed',
    )
    expect(logEntryMapIconKind(entry({ type: 'MOORED' }))).toBe('moored')
    expect(logEntryMapIconKind(entry({ type: 'CAST_OFF' }))).toBe('unmoored')
    expect(logEntryMapIconKind(entry({ type: 'SAILS_UP' }))).toBe('sails-up')
    expect(logEntryMapIconKind(entry({ type: 'SAILS_DOWN' }))).toBe('sails-down')
    expect(logEntryMapIconKind(entry({ type: 'ENGINE_ON' }))).toBe('engine-on')
    expect(logEntryMapIconKind(entry({ type: 'ENGINE_OFF' }))).toBe('engine-off')
    expect(logEntryMapIconKind(entry({ type: 'PHOTO' }))).toBe('photo')
    expect(logEntryMapIconKind(entry({ type: 'VOICE_NOTE' }))).toBe('voice')
    expect(logEntryMapIconKind(entry({ type: 'NOTE' }))).toBe('note')
    expect(logEntryMapIconKind(entry({ type: 'HOURLY_LOG' }))).toBe('hourly-log')
  })

  it('uses a compass icon for direction-change auto entries', () => {
    expect(
      logEntryMapIconKind(
        entry({
          type: 'HOURLY_LOG',
          data: { autoGenerated: true, source: 'heading-change' },
        }),
      ),
    ).toBe('direction-change')
  })

  it('uses a video icon when media is a video', () => {
    expect(
      logEntryMapIconKind(entry({ type: 'PHOTO', data: { video: true } })),
    ).toBe('video')
  })
})

describe('logEntryMapOutline', () => {
  it('uses a solid outline for human-created entries', () => {
    expect(logEntryMapOutline(entry({ type: 'NOTE' }))).toBe('solid')
    expect(logEntryHasHumanInput(entry({ type: 'SAILS_UP' }))).toBe(true)
  })

  it('uses a dotted outline for untouched auto entries', () => {
    expect(
      logEntryMapOutline(
        entry({
          type: 'HOURLY_LOG',
          notes: 'Auto-tracked position',
          data: { autoGenerated: true, source: 'background-gps' },
        }),
      ),
    ).toBe('dotted')
  })

  it('uses a solid outline once an auto entry has human input', () => {
    expect(
      logEntryMapOutline(
        entry({
          type: 'HOURLY_LOG',
          notes: 'Saw a pod of dolphins',
          data: { autoGenerated: true, source: 'background-gps' },
        }),
      ),
    ).toBe('solid')
    expect(
      logEntryMapOutline(
        entry({
          type: 'HOURLY_LOG',
          notes: 'Auto-tracked position',
          data: {
            autoGenerated: true,
            source: 'background-gps',
            humanEdited: true,
          },
        }),
      ),
    ).toBe('solid')
  })
})

describe('collapseColocatedLogEntries', () => {
  it('keeps the higher-priority type when entries share a position', () => {
    const visible = collapseColocatedLogEntries([
      entry({
        id: 'hourly',
        type: 'HOURLY_LOG',
        latitude: 48.1,
        longitude: -123.1,
      }),
      entry({
        id: 'anchor',
        type: 'ANCHOR_DROPPED',
        latitude: 48.1,
        longitude: -123.1,
      }),
      entry({
        id: 'note',
        type: 'NOTE',
        latitude: 48.2,
        longitude: -123.2,
      }),
    ])

    expect(visible.map((item) => item.id)).toEqual(['anchor', 'note'])
  })
})

describe('logEntryMapMarkerImageId', () => {
  it('strips color punctuation so MapLibre can use the id', () => {
    expect(logEntryMapMarkerImageId('photo', '#7ec8e8', 'dotted')).toBe(
      'log-entry-photo-7ec8e8-dotted',
    )
  })
})
