import type { LogEntry, LogEntryType } from '../domain/logbook'
import {
  AUTO_GENERATED_ENTRY_NOTE,
  isAutoGeneratedEntry,
  isHumanEditedAutoEntry,
} from '../domain/instrument-data'
import { sameMapPosition } from './logbook-entry-order'

export const LOG_ENTRY_MAP_ICON_KINDS = [
  'anchor-dropped',
  'anchor-weighed',
  'moored',
  'unmoored',
  'sails-up',
  'sails-down',
  'engine-on',
  'engine-off',
  'video',
  'photo',
  'media-photo',
  'media-video',
  'voice',
  'note',
  'hourly-log',
  'direction-change',
  'start-trip',
  'end-trip',
] as const

export type LogEntryMapIconKind = (typeof LOG_ENTRY_MAP_ICON_KINDS)[number]
export type LogEntryMapOutline = 'solid' | 'dotted'

/** Lower number wins when several entries share a map position. */
export const LOG_ENTRY_MAP_ICON_PRIORITY: Record<LogEntryMapIconKind, number> = {
  'anchor-dropped': 0,
  'anchor-weighed': 0,
  'moored': 1,
  'unmoored': 1,
  'sails-up': 2,
  'sails-down': 2,
  'engine-on': 3,
  'engine-off': 3,
  video: 4,
  photo: 5,
  'media-photo': 5,
  'media-video': 4,
  voice: 6,
  note: 7,
  'hourly-log': 8,
  'direction-change': 9,
  'start-trip': 10,
  'end-trip': 10,
}

const TYPE_TO_ICON_KIND: Record<LogEntryType, LogEntryMapIconKind> = {
  ANCHOR_DROPPED: 'anchor-dropped',
  ANCHOR_WEIGHED: 'anchor-weighed',
  MOORED: 'moored',
  CAST_OFF: 'unmoored',
  SAILS_UP: 'sails-up',
  SAILS_DOWN: 'sails-down',
  ENGINE_ON: 'engine-on',
  ENGINE_OFF: 'engine-off',
  PHOTO: 'photo',
  MEDIA: 'media-photo',
  VOICE_NOTE: 'voice',
  NOTE: 'note',
  HOURLY_LOG: 'hourly-log',
  START_TRIP: 'start-trip',
  END_TRIP: 'end-trip',
}

function dataString(
  data: Record<string, unknown> | null | undefined,
  key: string,
): string | null {
  const value = data?.[key]
  return typeof value === 'string' ? value : null
}

export function isDirectionChangeEntry(
  entry: Pick<LogEntry, 'type' | 'data'>,
): boolean {
  if ((entry.type as string) === 'DIRECTION_CHANGE') return true
  const source = dataString(entry.data, 'source')?.toLowerCase()
  const reason = dataString(entry.data, 'reason')?.toLowerCase()
  const autoKind = dataString(entry.data, 'autoKind')?.toLowerCase()
  return (
    source === 'heading-change' ||
    source === 'direction-change' ||
    source === 'course-change' ||
    reason === 'direction-change' ||
    reason === 'heading-change' ||
    autoKind === 'direction-change'
  )
}

export function isVideoLogEntry(entry: Pick<LogEntry, 'type' | 'data'>): boolean {
  if ((entry.type as string) === 'VIDEO') return true
  if (entry.data?.video === true) return true
  const mediaType = dataString(entry.data, 'mediaType')?.toLowerCase()
  const kind = dataString(entry.data, 'kind')?.toLowerCase()
  return mediaType === 'video' || kind === 'video'
}

export function isMediaMapEntry(
  entry: Pick<LogEntry, 'type' | 'data'>,
): boolean {
  return entry.type === 'MEDIA'
}

export function logEntryMapIconKind(
  entry: Pick<LogEntry, 'type' | 'data'>,
): LogEntryMapIconKind {
  if (isDirectionChangeEntry(entry)) return 'direction-change'
  if (entry.type === 'MEDIA') {
    return isVideoLogEntry(entry) ? 'media-video' : 'media-photo'
  }
  if (isVideoLogEntry(entry)) return 'video'
  return TYPE_TO_ICON_KIND[entry.type] ?? 'note'
}

export function logEntryHasHumanInput(
  entry: Pick<LogEntry, 'notes' | 'data'>,
): boolean {
  if (!isAutoGeneratedEntry(entry.data)) return true
  if (isHumanEditedAutoEntry(entry.data)) return true
  const notes = entry.notes?.trim() ?? ''
  return notes.length > 0 && notes !== AUTO_GENERATED_ENTRY_NOTE
}

export function logEntryMapOutline(
  entry: Pick<LogEntry, 'notes' | 'data'>,
): LogEntryMapOutline {
  return logEntryHasHumanInput(entry) ? 'solid' : 'dotted'
}

export function logEntryMapMarkerImageId(
  kind: LogEntryMapIconKind,
  color: string,
  outline: LogEntryMapOutline,
): string {
  const safeColor = color.replace(/[^a-zA-Z0-9]/g, '').toLowerCase()
  return `log-entry-${kind}-${safeColor}-${outline}`
}

export function pickDominantLogEntry<T extends LogEntry>(entries: T[]): T {
  return entries.reduce((best, entry) => {
    const bestRank = LOG_ENTRY_MAP_ICON_PRIORITY[logEntryMapIconKind(best)]
    const nextRank = LOG_ENTRY_MAP_ICON_PRIORITY[logEntryMapIconKind(entry)]
    if (nextRank < bestRank) return entry
    if (nextRank > bestRank) return best
    return entry
  })
}

/** Keep one marker per identical lat/lng, preferring the higher-priority type. */
export function collapseColocatedLogEntries<T extends LogEntry>(entries: T[]): T[] {
  const groups: T[][] = []

  for (const entry of entries) {
    const group = groups.find((candidates) => {
      const first = candidates[0]
      return first != null && sameMapPosition(first, entry)
    })
    if (group) {
      group.push(entry)
      continue
    }
    groups.push([entry])
  }

  return groups.map((group) => pickDominantLogEntry(group))
}
