import type { LogEntry, LogEntryType, Media } from '../domain/logbook'
import {
  AUTO_GENERATED_ENTRY_NOTE,
  isAutoGeneratedEntry,
  isHumanEditedAutoEntry,
} from '../domain/instrument-data'
import { isTripWaypointEntry } from './route-map-marker'
import { sameMapPosition } from './logbook-entry-order'
import { isVideoMediaFileName } from './media-entry'

export const LOG_ENTRY_MAP_ICON_KINDS = [
  'waypoint-active',
  'waypoint',
  'anchor-dropped',
  'anchor-weighed',
  'moored',
  'unmoored',
  'sails-up',
  'sails-down',
  'engine-on',
  'engine-off',
  'video',
  'photo',
  'media-photo',
  'media-video',
  'voice',
  'note',
  'hourly-log',
  'direction-change',
  'start-trip',
  'end-trip',
] as const

export type LogEntryMapIconKind = (typeof LOG_ENTRY_MAP_ICON_KINDS)[number]
export type LogEntryMapOutline = 'solid' | 'dotted'

/** Lower number wins when several entries share a map position. */
export const LOG_ENTRY_MAP_ICON_PRIORITY: Record<LogEntryMapIconKind, number> =
  {
    'waypoint-active': -1,
    waypoint: 0,
    'anchor-dropped': 1,
    'anchor-weighed': 1,
    moored: 2,
    unmoored: 2,
    'sails-up': 3,
    'sails-down': 3,
    'engine-on': 4,
    'engine-off': 4,
    video: 5,
    photo: 6,
    'media-photo': 6,
    'media-video': 5,
    voice: 7,
    note: 8,
    'hourly-log': 9,
    'direction-change': 10,
    'start-trip': 11,
    'end-trip': 11,
  }

const TYPE_TO_ICON_KIND: Record<LogEntryType, LogEntryMapIconKind> = {
  ANCHOR_DROPPED: 'anchor-dropped',
  ANCHOR_WEIGHED: 'anchor-weighed',
  MOORED: 'moored',
  CAST_OFF: 'unmoored',
  SAILS_UP: 'sails-up',
  SAILS_DOWN: 'sails-down',
  ENGINE_ON: 'engine-on',
  ENGINE_OFF: 'engine-off',
  PHOTO: 'photo',
  MEDIA: 'media-photo',
  VOICE_NOTE: 'voice',
  NOTE: 'note',
  HOURLY_LOG: 'hourly-log',
  START_TRIP: 'start-trip',
  END_TRIP: 'end-trip',
}

function dataString(
  data: Record<string, unknown> | null | undefined,
  key: string,
): string | null {
  const value = data?.[key]
  return typeof value === 'string' ? value : null
}

export function isDirectionChangeEntry(
  entry: Pick<LogEntry, 'type' | 'data'>,
): boolean {
  if ((entry.type as string) === 'DIRECTION_CHANGE') return true
  const source = dataString(entry.data, 'source')?.toLowerCase()
  const reason = dataString(entry.data, 'reason')?.toLowerCase()
  const autoKind = dataString(entry.data, 'autoKind')?.toLowerCase()
  return (
    source === 'heading-change' ||
    source === 'direction-change' ||
    source === 'course-change' ||
    reason === 'direction-change' ||
    reason === 'heading-change' ||
    autoKind === 'direction-change'
  )
}

export function isVideoLogEntry(
  entry: Pick<LogEntry, 'type' | 'data'>,
): boolean {
  if ((entry.type as string) === 'VIDEO') return true
  if (entry.data?.video === true) return true
  const mediaType = dataString(entry.data, 'mediaType')?.toLowerCase()
  const kind = dataString(entry.data, 'kind')?.toLowerCase()
  return mediaType === 'video' || kind === 'video'
}

export function isMediaMapEntry(
  entry: Pick<LogEntry, 'type' | 'data'>,
): boolean {
  return entry.type === 'MEDIA'
}

export type LogEntryMapMedia = Pick<
  Media,
  'type' | 'localPath' | 'remoteUrl' | 'thumbnailUrl'
>

function mediaLooksLikeVideo(media: LogEntryMapMedia[]): boolean {
  return media.some((item) => {
    if (item.type === 'voice') return false
    return (
      isVideoMediaFileName(item.localPath) ||
      isVideoMediaFileName(item.remoteUrl) ||
      isVideoMediaFileName(item.thumbnailUrl)
    )
  })
}

export function logEntryMapThumbnailUrl(
  media: LogEntryMapMedia[],
): string | null {
  const items = media.filter((item) => item.type !== 'voice')
  for (const item of items) {
    if (item.thumbnailUrl) return item.thumbnailUrl
  }
  for (const item of items) {
    if (mediaLooksLikeVideo([item])) continue
    const source = item.remoteUrl ?? item.localPath
    if (source) return source
  }
  return null
}

export function logEntryMapIconKind(
  entry: Pick<LogEntry, 'type' | 'data'>,
  options?: { activeWaypoint?: boolean; media?: LogEntryMapMedia[] },
): LogEntryMapIconKind {
  if (isTripWaypointEntry(entry.data)) {
    return options?.activeWaypoint ? 'waypoint-active' : 'waypoint'
  }
  if (isDirectionChangeEntry(entry)) return 'direction-change'
  const media = options?.media ?? []
  const thumbnailUrl = logEntryMapThumbnailUrl(media)
  const videoMedia = mediaLooksLikeVideo(media)
  if (entry.type === 'MEDIA') {
    return isVideoLogEntry(entry) || videoMedia ? 'media-video' : 'media-photo'
  }
  if (isVideoLogEntry(entry) || videoMedia) {
    return entry.type === 'PHOTO' || !thumbnailUrl ? 'video' : 'media-video'
  }
  if (entry.type === 'PHOTO') {
    return thumbnailUrl ? 'media-photo' : 'photo'
  }
  if (thumbnailUrl && (entry.type === 'HOURLY_LOG' || entry.type === 'NOTE')) {
    return 'media-photo'
  }
  return TYPE_TO_ICON_KIND[entry.type] ?? 'note'
}

export function logEntryHasHumanInput(
  entry: Pick<LogEntry, 'notes' | 'data'>,
): boolean {
  if (!isAutoGeneratedEntry(entry.data)) return true
  if (isHumanEditedAutoEntry(entry.data)) return true
  const notes = entry.notes?.trim() ?? ''
  return notes.length > 0 && notes !== AUTO_GENERATED_ENTRY_NOTE
}

export function logEntryMapOutline(
  entry: Pick<LogEntry, 'notes' | 'data'>,
): LogEntryMapOutline {
  return logEntryHasHumanInput(entry) ? 'solid' : 'dotted'
}

export function logEntryMapMarkerImageId(
  kind: LogEntryMapIconKind,
  color: string,
  outline: LogEntryMapOutline,
  thumbnailKey?: string | null,
): string {
  const safeColor = color.replace(/[^a-zA-Z0-9]/g, '').toLowerCase()
  const base = `log-entry-${kind}-${safeColor}-${outline}`
  if (!thumbnailKey) return base
  const safeKey = thumbnailKey.replace(/[^a-zA-Z0-9]/g, '').slice(0, 32)
  return safeKey ? `${base}-${safeKey}` : base
}

function iconKindForEntry<T extends LogEntry>(
  entry: T,
  mediaByEntry?: Map<string, LogEntryMapMedia[]>,
): LogEntryMapIconKind {
  return logEntryMapIconKind(entry, { media: mediaByEntry?.get(entry.id) })
}

export function pickDominantLogEntry<T extends LogEntry>(
  entries: T[],
  mediaByEntry?: Map<string, LogEntryMapMedia[]>,
): T {
  return entries.reduce((best, entry) => {
    const bestRank =
      LOG_ENTRY_MAP_ICON_PRIORITY[iconKindForEntry(best, mediaByEntry)]
    const nextRank =
      LOG_ENTRY_MAP_ICON_PRIORITY[iconKindForEntry(entry, mediaByEntry)]
    if (nextRank < bestRank) return entry
    if (nextRank > bestRank) return best
    return entry
  })
}

/** Keep one marker per identical lat/lng, preferring the higher-priority type. */
export function collapseColocatedLogEntries<T extends LogEntry>(
  entries: T[],
  mediaByEntry?: Map<string, LogEntryMapMedia[]>,
): T[] {
  const groups: T[][] = []

  for (const entry of entries) {
    const group = groups.find((candidates) => {
      const first = candidates[0]
      return first != null && sameMapPosition(first, entry)
    })
    if (group) {
      group.push(entry)
      continue
    }
    groups.push([entry])
  }

  return groups.map((group) => pickDominantLogEntry(group, mediaByEntry))
}
