import type { LogEntryType } from '../domain/logbook'

const types: LogEntryType[] = [
  'START_TRIP',
  'SAILS_UP',
  'ENGINE_ON',
  'ENGINE_OFF',
  'SAILS_DOWN',
  'ANCHOR_DROPPED',
  'ANCHOR_WEIGHED',
  'MOORED',
  'CAST_OFF',
  'END_TRIP',
  'NOTE',
  'HOURLY_LOG',
  'PHOTO',
  'VOICE_NOTE',
  'MEDIA',
]
export type TripLogTranslationKey = `tripLog_${LogEntryType}`
const labels: Record<string, string[]> = {
  en: [
    'Trip started',
    'Sails raised',
    'Engine on',
    'Engine off',
    'Sails lowered',
    'Anchor dropped',
    'Anchor weighed',
    'Moored',
    'Cast off',
    'Trip ended',
    'Note',
    'Hourly log',
    'Photo',
    'Voice note',
    'Media',
  ],
  sv: [
    'Turen startad',
    'Seglen hissade',
    'Motorn på',
    'Motorn av',
    'Seglen nedtagna',
    'Ankaret fällt',
    'Ankaret lättat',
    'Förtöjd',
    'Kastat loss',
    'Turen avslutad',
    'Anteckning',
    'Timlogg',
    'Foto',
    'Röstanteckning',
    'Media',
  ],
  da: [
    'Turen startet',
    'Sejl hejst',
    'Motor tændt',
    'Motor slukket',
    'Sejl sænket',
    'Anker kastet',
    'Anker lettet',
    'Fortøjet',
    'Kastet los',
    'Turen afsluttet',
    'Note',
    'Timelog',
    'Foto',
    'Talebesked',
    'Medier',
  ],
  de: [
    'Fahrt begonnen',
    'Segel gesetzt',
    'Motor an',
    'Motor aus',
    'Segel geborgen',
    'Anker geworfen',
    'Anker gelichtet',
    'Festgemacht',
    'Leinen los',
    'Fahrt beendet',
    'Notiz',
    'Stündlicher Logeintrag',
    'Foto',
    'Sprachnotiz',
    'Medien',
  ],
  es: [
    'Travesía iniciada',
    'Velas izadas',
    'Motor encendido',
    'Motor apagado',
    'Velas arriadas',
    'Ancla fondeada',
    'Ancla levada',
    'Amarrado',
    'Amarras largadas',
    'Travesía finalizada',
    'Nota',
    'Registro horario',
    'Foto',
    'Nota de voz',
    'Multimedia',
  ],
  fr: [
    'Sortie commencée',
    'Voiles hissées',
    'Moteur allumé',
    'Moteur arrêté',
    'Voiles affalées',
    'Ancre mouillée',
    'Ancre levée',
    'Amarré',
    'Amarres larguées',
    'Sortie terminée',
    'Note',
    'Relevé horaire',
    'Photo',
    'Note vocale',
    'Médias',
  ],
  nl: [
    'Tocht begonnen',
    'Zeilen gehesen',
    'Motor aan',
    'Motor uit',
    'Zeilen gestreken',
    'Anker uitgegooid',
    'Anker gelicht',
    'Afgemeerd',
    'Losgegooid',
    'Tocht beëindigd',
    'Notitie',
    'Uurlog',
    'Foto',
    'Spraaknotitie',
    'Media',
  ],
  pt: [
    'Viagem iniciada',
    'Velas içadas',
    'Motor ligado',
    'Motor desligado',
    'Velas arriadas',
    'Âncora lançada',
    'Âncora içada',
    'Amarrado',
    'Amarras largadas',
    'Viagem terminada',
    'Nota',
    'Registro horário',
    'Foto',
    'Nota de voz',
    'Mídia',
  ],
  fi: [
    'Matka aloitettu',
    'Purjeet nostettu',
    'Moottori käynnissä',
    'Moottori sammutettu',
    'Purjeet laskettu',
    'Ankkuri laskettu',
    'Ankkuri nostettu',
    'Kiinnitetty',
    'Köydet irrotettu',
    'Matka päättynyt',
    'Muistiinpano',
    'Tuntiloki',
    'Valokuva',
    'Äänimuistiinpano',
    'Media',
  ],
  el: [
    'Έναρξη ταξιδιού',
    'Πανιά ανεβασμένα',
    'Μηχανή σε λειτουργία',
    'Μηχανή σβηστή',
    'Πανιά κατεβασμένα',
    'Άγκυρα ποντισμένη',
    'Άγκυρα σηκωμένη',
    'Πρόσδεση',
    'Απόπλους',
    'Τέλος ταξιδιού',
    'Σημείωση',
    'Ωριαία καταγραφή',
    'Φωτογραφία',
    'Φωνητική σημείωση',
    'Πολυμέσα',
  ],
  tr: [
    'Seyir başladı',
    'Yelkenler açıldı',
    'Motor çalışıyor',
    'Motor durduruldu',
    'Yelkenler indirildi',
    'Demir atıldı',
    'Demir alındı',
    'Bağlandı',
    'Halatlar fora edildi',
    'Seyir sona erdi',
    'Not',
    'Saatlik kayıt',
    'Fotoğraf',
    'Sesli not',
    'Medya',
  ],
  vi: [
    'Bắt đầu chuyến đi',
    'Đã giương buồm',
    'Bật động cơ',
    'Tắt động cơ',
    'Đã hạ buồm',
    'Đã thả neo',
    'Đã nhổ neo',
    'Đã buộc tàu',
    'Đã tháo dây neo',
    'Kết thúc chuyến đi',
    'Ghi chú',
    'Nhật ký hàng giờ',
    'Ảnh',
    'Ghi chú giọng nói',
    'Đa phương tiện',
  ],
  zh: [
    '航程开始',
    '已升帆',
    '发动机启动',
    '发动机关闭',
    '已降帆',
    '已抛锚',
    '已起锚',
    '已系泊',
    '已解缆',
    '航程结束',
    '备注',
    '每小时日志',
    '照片',
    '语音备注',
    '媒体',
  ],
  yue: [
    '航程開始',
    '已升帆',
    '引擎啟動',
    '引擎關閉',
    '已降帆',
    '已拋錨',
    '已起錨',
    '已繫泊',
    '已解纜',
    '航程結束',
    '備註',
    '每小時日誌',
    '相片',
    '語音備註',
    '媒體',
  ],
  ja: [
    '航海開始',
    '帆を上げました',
    'エンジン始動',
    'エンジン停止',
    '帆を下げました',
    '投錨',
    '抜錨',
    '係留',
    '出港',
    '航海終了',
    'メモ',
    '毎時の記録',
    '写真',
    '音声メモ',
    'メディア',
  ],
  ko: [
    '항해 시작',
    '돛 올림',
    '엔진 켜짐',
    '엔진 꺼짐',
    '돛 내림',
    '투묘',
    '양묘',
    '계류',
    '출항',
    '항해 종료',
    '메모',
    '시간별 기록',
    '사진',
    '음성 메모',
    '미디어',
  ],
  ar: [
    'بدأت الرحلة',
    'رُفعت الأشرعة',
    'شُغّل المحرك',
    'أُوقف المحرك',
    'أُنزلت الأشرعة',
    'أُلقيت المرساة',
    'رُفعت المرساة',
    'تم الرسو',
    'تم فك الحبال',
    'انتهت الرحلة',
    'ملاحظة',
    'السجل الساعي',
    'صورة',
    'ملاحظة صوتية',
    'وسائط',
  ],
}
export function tripLogCopy(
  language: string,
): Record<TripLogTranslationKey, string> {
  return Object.fromEntries(
    types.map((type, index) => [
      `tripLog_${type}`,
      (labels[language] ?? labels.en)[index],
    ]),
  ) as Record<TripLogTranslationKey, string>
}
