import type { AssetBrand } from './asset-brands'

// Curated marine equipment brands, alphabetically ordered.
// Logo provenance and maintenance notes live in public/brands.
export const ASSET_BRAND_CATALOG: AssetBrand[] = [
  {
    id: 'ab-inflatables',
    name: 'AB Inflatables',
    aliases: [],
    logo: '/brands/ab-inflatables.webp',
  },
  {
    id: 'achilles',
    name: 'Achilles',
    aliases: [],
    logo: null,
  },
  {
    id: 'acr-electronics',
    name: 'ACR Electronics',
    aliases: ['ACR'],
    logo: '/brands/acr-electronics.png',
  },
  {
    id: 'actisense',
    name: 'Actisense',
    aliases: [],
    logo: '/brands/actisense.svg',
  },
  {
    id: 'airmar',
    name: 'Airmar',
    aliases: [],
    logo: '/brands/airmar.png',
  },
  {
    id: 'allen-brothers',
    name: 'Allen Brothers',
    aliases: ['Allen'],
    logo: '/brands/allen-brothers.jpg',
  },
  {
    id: 'amec',
    name: 'AMEC',
    aliases: ['Alltek Marine'],
    logo: '/brands/amec.png',
    whiteLogo: true,
  },
  {
    id: 'ancor',
    name: 'Ancor',
    aliases: ['Ancor Marine'],
    logo: '/brands/ancor.svg',
  },
  {
    id: 'andersen',
    name: 'Andersen',
    aliases: ['Andersen Winches'],
    logo: '/brands/andersen.webp',
    whiteLogo: true,
  },
  {
    id: 'antal',
    name: 'Antal',
    aliases: [],
    logo: '/brands/antal.svg',
  },
  {
    id: 'aqua-signal',
    name: 'Aqua Signal',
    aliases: ['Aquasignal'],
    logo: null,
  },
  {
    id: 'attwood',
    name: 'Attwood',
    aliases: [],
    logo: '/brands/attwood.svg',
  },
  {
    id: 'autoterm',
    name: 'Autoterm',
    aliases: ['Planar'],
    logo: '/brands/autoterm.png',
  },
  {
    id: 'b-and-g',
    name: 'B&G',
    aliases: ['B and G', 'B & G', 'Brookes and Gatehouse'],
    logo: '/brands/b-and-g.png',
  },
  {
    id: 'balmar',
    name: 'Balmar',
    aliases: [],
    logo: '/brands/balmar.jpg',
  },
  {
    id: 'baltic',
    name: 'Baltic',
    aliases: ['Baltic Lifejackets'],
    logo: '/brands/baltic.svg',
    inferFromName: false,
  },
  {
    id: 'barton-marine',
    name: 'Barton Marine',
    aliases: ['Barton'],
    logo: null,
  },
  {
    id: 'battle-born-batteries',
    name: 'Battle Born Batteries',
    aliases: ['Battle Born'],
    logo: '/brands/battle-born-batteries.svg',
  },
  {
    id: 'bennett-marine',
    name: 'Bennett Marine',
    aliases: ['Bennett'],
    logo: null,
  },
  {
    id: 'bep-marine',
    name: 'BEP Marine',
    aliases: ['BEP', 'Bepmarine'],
    logo: null,
  },
  {
    id: 'beta-marine',
    name: 'Beta Marine',
    aliases: [],
    logo: '/brands/beta-marine.jpg',
  },
  {
    id: 'blue-sea-systems',
    name: 'Blue Sea Systems',
    aliases: ['Blue Sea'],
    logo: null,
  },
  {
    id: 'caframo',
    name: 'Caframo',
    aliases: [],
    logo: '/brands/caframo.svg',
  },
  {
    id: 'calypso-instruments',
    name: 'Calypso Instruments',
    aliases: ['Calypso'],
    logo: '/brands/calypso-instruments.png',
  },
  {
    id: 'cobra-marine',
    name: 'Cobra Marine',
    aliases: ['Cobra'],
    logo: '/brands/cobra-marine.svg',
  },
  {
    id: 'crewsaver',
    name: 'Crewsaver',
    aliases: [],
    logo: '/brands/crewsaver.png',
    whiteLogo: true,
  },
  {
    id: 'cristec',
    name: 'Cristec',
    aliases: [],
    logo: '/brands/cristec.png',
  },
  {
    id: 'ctek',
    name: 'CTEK',
    aliases: [],
    logo: null,
  },
  {
    id: 'cummins-onan',
    name: 'Cummins Onan',
    aliases: ['Onan'],
    logo: null,
  },
  {
    id: 'davis-instruments',
    name: 'Davis Instruments',
    aliases: ['Davis'],
    logo: '/brands/davis-instruments.webp',
  },
  {
    id: 'dickinson-marine',
    name: 'Dickinson Marine',
    aliases: ['Dickinson'],
    logo: null,
  },
  {
    id: 'digital-antenna',
    name: 'Digital Antenna',
    aliases: [],
    logo: null,
  },
  {
    id: 'digital-yacht',
    name: 'Digital Yacht',
    aliases: [],
    logo: null,
  },
  {
    id: 'dolphin-charger',
    name: 'Dolphin Charger',
    aliases: ['Dolphin'],
    logo: null,
  },
  {
    id: 'dometic',
    name: 'Dometic',
    aliases: [],
    logo: '/brands/dometic.svg',
  },
  {
    id: 'eberspacher',
    name: 'Eberspächer',
    aliases: ['Eberspacher', 'Espar'],
    logo: '/brands/eberspacher.svg',
  },
  {
    id: 'em-trak',
    name: 'em-trak',
    aliases: ['Em Trak'],
    logo: null,
  },
  {
    id: 'engel',
    name: 'Engel',
    aliases: [],
    logo: null,
  },
  {
    id: 'eno',
    name: 'ENO',
    aliases: [],
    logo: '/brands/eno.svg',
    whiteLogo: true,
  },
  {
    id: 'epropulsion',
    name: 'ePropulsion',
    aliases: ['e Propulsion'],
    logo: '/brands/epropulsion.png',
  },
  {
    id: 'evinrude',
    name: 'Evinrude',
    aliases: ['BRP Evinrude'],
    logo: null,
  },
  {
    id: 'facnor',
    name: 'Facnor',
    aliases: [],
    logo: '/brands/facnor.png',
    whiteLogo: true,
  },
  {
    id: 'faria-beede',
    name: 'Faria Beede',
    aliases: ['Faria', 'Faria Instruments'],
    logo: '/brands/faria-beede.svg',
    whiteLogo: true,
  },
  {
    id: 'fell-marine',
    name: 'Fell Marine',
    aliases: [],
    logo: null,
  },
  {
    id: 'fireboy-xintex',
    name: 'Fireboy-Xintex',
    aliases: ['Fireboy', 'Xintex'],
    logo: '/brands/fireboy-xintex.png',
  },
  {
    id: 'fischer-panda',
    name: 'Fischer Panda',
    aliases: [],
    logo: '/brands/fischer-panda.svg',
    whiteLogo: true,
  },
  {
    id: 'flexofold',
    name: 'Flexofold',
    aliases: [],
    logo: '/brands/flexofold.svg',
    whiteLogo: true,
  },
  {
    id: 'flir',
    name: 'FLIR',
    aliases: ['FLIR Maritime'],
    logo: '/brands/flir.svg',
  },
  {
    id: 'flojet',
    name: 'Flojet',
    aliases: [],
    logo: null,
  },
  {
    id: 'force-10',
    name: 'Force 10',
    aliases: [],
    logo: '/brands/force-10.svg',
    inferFromName: false,
  },
  {
    id: 'fortress-anchors',
    name: 'Fortress Anchors',
    aliases: ['Fortress'],
    logo: '/brands/fortress-anchors.png',
  },
  {
    id: 'furlex',
    name: 'Furlex',
    aliases: [],
    logo: null,
  },
  {
    id: 'furuno',
    name: 'Furuno',
    aliases: [],
    logo: '/brands/furuno.jpg',
  },
  {
    id: 'fusion',
    name: 'Fusion',
    aliases: ['Fusion Marine', 'Fusion Entertainment'],
    logo: null,
    inferFromName: false,
  },
  {
    id: 'garmin',
    name: 'Garmin',
    aliases: [],
    logo: '/brands/garmin.svg',
  },
  {
    id: 'gill',
    name: 'Gill',
    aliases: ['Gill Marine'],
    logo: '/brands/gill.png',
  },
  {
    id: 'gleistein',
    name: 'Gleistein',
    aliases: [],
    logo: '/brands/gleistein.png',
  },
  {
    id: 'glomex',
    name: 'Glomex',
    aliases: [],
    logo: '/brands/glomex.png',
  },
  {
    id: 'gme',
    name: 'GME',
    aliases: [],
    logo: '/brands/gme.png',
  },
  {
    id: 'gori',
    name: 'Gori',
    aliases: ['Gori Propeller'],
    logo: '/brands/gori.svg',
  },
  {
    id: 'groco',
    name: 'Groco',
    aliases: [],
    logo: '/brands/groco.png',
  },
  {
    id: 'harken',
    name: 'Harken',
    aliases: [],
    logo: null,
  },
  {
    id: 'hella-marine',
    name: 'Hella Marine',
    aliases: [],
    logo: '/brands/hella-marine.png',
  },
  {
    id: 'helly-hansen',
    name: 'Helly Hansen',
    aliases: [],
    logo: '/brands/helly-hansen.png',
  },
  {
    id: 'highfield',
    name: 'Highfield',
    aliases: ['Highfield Boats'],
    logo: '/brands/highfield.png',
  },
  {
    id: 'honda',
    name: 'Honda',
    aliases: ['Honda Marine'],
    logo: '/brands/honda.png',
  },
  {
    id: 'humminbird',
    name: 'Humminbird',
    aliases: [],
    logo: null,
  },
  {
    id: 'icom',
    name: 'Icom',
    aliases: [],
    logo: '/brands/icom.png',
  },
  {
    id: 'intellian',
    name: 'Intellian',
    aliases: ['Intellian Technologies'],
    logo: null,
  },
  {
    id: 'iridium',
    name: 'Iridium',
    aliases: [],
    logo: null,
  },
  {
    id: 'isotemp',
    name: 'Isotemp',
    aliases: [],
    logo: null,
  },
  {
    id: 'isotherm',
    name: 'Isotherm',
    aliases: [],
    logo: '/brands/isotherm.png',
  },
  {
    id: 'jabsco',
    name: 'Jabsco',
    aliases: [],
    logo: '/brands/jabsco.png',
  },
  {
    id: 'jbl',
    name: 'JBL',
    aliases: [],
    logo: null,
  },
  {
    id: 'jl-audio',
    name: 'JL Audio',
    aliases: [],
    logo: null,
  },
  {
    id: 'johnson-pump',
    name: 'Johnson Pump',
    aliases: ['SPX Johnson Pump'],
    logo: '/brands/johnson-pump.png',
  },
  {
    id: 'jonbuoy',
    name: 'Jonbuoy',
    aliases: ['Jon Buoy'],
    logo: null,
  },
  {
    id: 'karver',
    name: 'Karver',
    aliases: [],
    logo: '/brands/karver.png',
  },
  {
    id: 'katadyn',
    name: 'Katadyn',
    aliases: [],
    logo: '/brands/katadyn.gif',
  },
  {
    id: 'kohler',
    name: 'Kohler',
    aliases: ['Kohler Marine'],
    logo: null,
  },
  {
    id: 'kus',
    name: 'KUS',
    aliases: ['Wema'],
    logo: '/brands/kus.png',
  },
  {
    id: 'kvh',
    name: 'KVH',
    aliases: ['KVH Industries'],
    logo: '/brands/kvh.svg',
  },
  {
    id: 'lalizas',
    name: 'Lalizas',
    aliases: [],
    logo: '/brands/lalizas.png',
  },
  {
    id: 'lenco',
    name: 'Lenco',
    aliases: ['Lenco Marine'],
    logo: '/brands/lenco.svg',
  },
  {
    id: 'lewmar',
    name: 'Lewmar',
    aliases: [],
    logo: '/brands/lewmar.png',
  },
  {
    id: 'lifeline',
    name: 'Lifeline',
    aliases: ['Lifeline Batteries'],
    logo: '/brands/lifeline.png',
    whiteLogo: true,
  },
  {
    id: 'liros',
    name: 'LIROS',
    aliases: [],
    logo: '/brands/liros.png',
  },
  {
    id: 'lofrans',
    name: 'Lofrans',
    aliases: ["Lofrans'", 'Lofrans’'],
    logo: '/brands/lofrans.png',
  },
  {
    id: 'lopolight',
    name: 'Lopolight',
    aliases: [],
    logo: null,
  },
  {
    id: 'lowrance',
    name: 'Lowrance',
    aliases: [],
    logo: '/brands/lowrance.svg',
  },
  {
    id: 'lumishore',
    name: 'Lumishore',
    aliases: [],
    logo: null,
  },
  {
    id: 'lumitec',
    name: 'Lumitec',
    aliases: [],
    logo: '/brands/lumitec.jpg',
  },
  {
    id: 'magma',
    name: 'Magma',
    aliases: ['Magma Products'],
    logo: '/brands/magma.webp',
  },
  {
    id: 'mantus-marine',
    name: 'Mantus Marine',
    aliases: ['Mantus'],
    logo: '/brands/mantus-marine.png',
  },
  {
    id: 'maretron',
    name: 'Maretron',
    aliases: [],
    logo: null,
  },
  {
    id: 'marinco',
    name: 'Marinco',
    aliases: [],
    logo: '/brands/marinco.svg',
  },
  {
    id: 'marlow-ropes',
    name: 'Marlow Ropes',
    aliases: ['Marlow'],
    logo: '/brands/marlow-ropes.png',
  },
  {
    id: 'mastervolt',
    name: 'Mastervolt',
    aliases: [],
    logo: '/brands/mastervolt.png',
  },
  {
    id: 'max-power',
    name: 'Max Power',
    aliases: ['Maxpower'],
    logo: '/brands/max-power.png',
  },
  {
    id: 'max-prop',
    name: 'Max-Prop',
    aliases: ['Max Prop'],
    logo: '/brands/max-prop.webp',
    whiteLogo: true,
  },
  {
    id: 'maxwell',
    name: 'Maxwell',
    aliases: ['Maxwell Marine'],
    logo: '/brands/maxwell.webp',
  },
  {
    id: 'mcmurdo',
    name: 'McMurdo',
    aliases: [],
    logo: null,
  },
  {
    id: 'mercruiser',
    name: 'MerCruiser',
    aliases: ['Mercury MerCruiser'],
    logo: null,
  },
  {
    id: 'mercury',
    name: 'Mercury',
    aliases: ['Mercury Marine'],
    logo: null,
  },
  {
    id: 'michigan-wheel',
    name: 'Michigan Wheel',
    aliases: [],
    logo: '/brands/michigan-wheel.svg',
    whiteLogo: true,
  },
  {
    id: 'minn-kota',
    name: 'Minn Kota',
    aliases: [],
    logo: null,
  },
  {
    id: 'motorguide',
    name: 'MotorGuide',
    aliases: [],
    logo: null,
  },
  {
    id: 'mustang-survival',
    name: 'Mustang Survival',
    aliases: [],
    logo: '/brands/mustang-survival.svg',
  },
  {
    id: 'nanni',
    name: 'Nanni',
    aliases: ['Nanni Diesel'],
    logo: '/brands/nanni.svg',
  },
  {
    id: 'nasa-marine',
    name: 'NASA Marine',
    aliases: ['Nasa'],
    logo: '/brands/nasa-marine.png',
  },
  {
    id: 'navpod',
    name: 'NavPod',
    aliases: [],
    logo: null,
  },
  {
    id: 'newmar',
    name: 'Newmar',
    aliases: [],
    logo: '/brands/newmar.png',
    whiteLogo: true,
  },
  {
    id: 'noco',
    name: 'NOCO',
    aliases: [],
    logo: '/brands/noco.svg',
    whiteLogo: true,
  },
  {
    id: 'norcold',
    name: 'Norcold',
    aliases: [],
    logo: null,
  },
  {
    id: 'northern-lights',
    name: 'Northern Lights',
    aliases: [],
    logo: '/brands/northern-lights.png',
    inferFromName: false,
  },
  {
    id: 'ocean-safety',
    name: 'Ocean Safety',
    aliases: [],
    logo: '/brands/ocean-safety.png',
  },
  {
    id: 'ocean-signal',
    name: 'Ocean Signal',
    aliases: [],
    logo: '/brands/ocean-signal.svg',
    whiteLogo: true,
  },
  {
    id: 'oceanled',
    name: 'OceanLED',
    aliases: ['Ocean LED'],
    logo: null,
  },
  {
    id: 'odyssey-battery',
    name: 'Odyssey Battery',
    aliases: ['Odyssey'],
    logo: null,
  },
  {
    id: 'peplink',
    name: 'Peplink',
    aliases: [],
    logo: '/brands/peplink.svg',
    whiteLogo: true,
  },
  {
    id: 'perko',
    name: 'Perko',
    aliases: [],
    logo: '/brands/perko.png',
  },
  {
    id: 'plastimo',
    name: 'Plastimo',
    aliases: [],
    logo: '/brands/plastimo.png',
  },
  {
    id: 'polyform-norway',
    name: 'Polyform Norway',
    aliases: [],
    logo: '/brands/polyform-norway.jpg',
  },
  {
    id: 'polyform-us',
    name: 'Polyform US',
    aliases: ['Polyform U.S.', 'Polyform USA'],
    logo: null,
  },
  {
    id: 'profurl',
    name: 'Profurl',
    aliases: [],
    logo: '/brands/profurl.svg',
  },
  {
    id: 'promariner',
    name: 'ProMariner',
    aliases: [],
    logo: '/brands/promariner.svg',
  },
  {
    id: 'pss',
    name: 'PSS',
    aliases: ['PSS Shaft Seal'],
    logo: '/brands/pss.svg',
    whiteLogo: true,
  },
  {
    id: 'quark-elec',
    name: 'Quark-Elec',
    aliases: ['Quark Elec', 'QuarkElec'],
    logo: '/brands/quark-elec.png',
  },
  {
    id: 'quick',
    name: 'Quick',
    aliases: ['Quick Marine'],
    logo: '/brands/quick.png',
    inferFromName: false,
  },
  {
    id: 'racor',
    name: 'Racor',
    aliases: ['Parker Racor'],
    logo: null,
  },
  {
    id: 'railblaza',
    name: 'Railblaza',
    aliases: [],
    logo: '/brands/railblaza.png',
  },
  {
    id: 'rainman',
    name: 'Rainman',
    aliases: ['Rainman Watermakers'],
    logo: '/brands/rainman.png',
  },
  {
    id: 'raritan',
    name: 'Raritan',
    aliases: ['Raritan Engineering'],
    logo: '/brands/raritan.png',
  },
  {
    id: 'raymarine',
    name: 'Raymarine',
    aliases: ['Ray Marine'],
    logo: '/brands/raymarine.svg',
  },
  {
    id: 'relion',
    name: 'RELiON',
    aliases: ['Relion Battery'],
    logo: '/brands/relion.svg',
  },
  {
    id: 'renogy',
    name: 'Renogy',
    aliases: [],
    logo: null,
  },
  {
    id: 'ritchie-navigation',
    name: 'Ritchie Navigation',
    aliases: ['Ritchie'],
    logo: '/brands/ritchie-navigation.png',
    whiteLogo: true,
  },
  {
    id: 'robline',
    name: 'Robline',
    aliases: [],
    logo: '/brands/robline.png',
  },
  {
    id: 'rocna',
    name: 'Rocna',
    aliases: [],
    logo: '/brands/rocna.png',
  },
  {
    id: 'ronstan',
    name: 'Ronstan',
    aliases: [],
    logo: '/brands/ronstan.webp',
  },
  {
    id: 'rule',
    name: 'Rule',
    aliases: ['Rule Pumps'],
    logo: null,
    inferFromName: false,
  },
  {
    id: 'samson-rope',
    name: 'Samson Rope',
    aliases: ['Samson'],
    logo: '/brands/samson-rope.png',
    whiteLogo: true,
  },
  {
    id: 'scanstrut',
    name: 'Scanstrut',
    aliases: [],
    logo: '/brands/scanstrut.svg',
  },
  {
    id: 'schaefer-marine',
    name: 'Schaefer Marine',
    aliases: ['Schaefer'],
    logo: null,
  },
  {
    id: 'schenker',
    name: 'Schenker',
    aliases: ['Schenker Watermakers'],
    logo: '/brands/schenker.svg',
    whiteLogo: true,
  },
  {
    id: 'sea-dog',
    name: 'Sea-Dog',
    aliases: ['Sea Dog'],
    logo: '/brands/sea-dog.png',
  },
  {
    id: 'seaflo',
    name: 'SEAFLO',
    aliases: [],
    logo: '/brands/seaflo.png',
  },
  {
    id: 'seago',
    name: 'Seago',
    aliases: [],
    logo: null,
  },
  {
    id: 'seaview',
    name: 'Seaview',
    aliases: [],
    logo: '/brands/seaview.webp',
    whiteLogo: true,
  },
  {
    id: 'secumar',
    name: 'Secumar',
    aliases: [],
    logo: '/brands/secumar.png',
  },
  {
    id: 'selden',
    name: 'Seldén',
    aliases: ['Selden'],
    logo: null,
  },
  {
    id: 'shakespeare',
    name: 'Shakespeare',
    aliases: ['Shakespeare Marine'],
    logo: '/brands/shakespeare.svg',
    whiteLogo: true,
  },
  {
    id: 'shurflo',
    name: 'Shurflo',
    aliases: ['SHURflo'],
    logo: null,
  },
  {
    id: 'sierra',
    name: 'Sierra',
    aliases: ['Sierra Marine'],
    logo: null,
  },
  {
    id: 'silva',
    name: 'Silva',
    aliases: [],
    logo: '/brands/silva.webp',
    whiteLogo: true,
    inferFromName: false,
  },
  {
    id: 'simrad',
    name: 'Simrad',
    aliases: ['Simrad Yachting'],
    logo: '/brands/simrad.png',
  },
  {
    id: 'sionyx',
    name: 'SIONYX',
    aliases: [],
    logo: '/brands/sionyx.png',
    whiteLogo: true,
  },
  {
    id: 'sleipner',
    name: 'Sleipner',
    aliases: ['Side-Power', 'Side Power'],
    logo: '/brands/sleipner.svg',
  },
  {
    id: 'smartplug',
    name: 'SmartPlug',
    aliases: [],
    logo: '/brands/smartplug.png',
  },
  {
    id: 'solas',
    name: 'Solas',
    aliases: [],
    logo: '/brands/solas.png',
    inferFromName: false,
  },
  {
    id: 'spade',
    name: 'Spade',
    aliases: ['Spade Anchor'],
    logo: '/brands/spade.svg',
    whiteLogo: true,
    inferFromName: false,
  },
  {
    id: 'spectra-watermakers',
    name: 'Spectra Watermakers',
    aliases: ['Spectra'],
    logo: '/brands/spectra-watermakers.webp',
  },
  {
    id: 'spinlock',
    name: 'Spinlock',
    aliases: [],
    logo: '/brands/spinlock.png',
  },
  {
    id: 'standard-horizon',
    name: 'Standard Horizon',
    aliases: [],
    logo: '/brands/standard-horizon.jpg',
    inferFromName: false,
  },
  {
    id: 'starlink',
    name: 'Starlink',
    aliases: [],
    logo: '/brands/starlink.png',
    whiteLogo: true,
  },
  {
    id: 'sterling-power',
    name: 'Sterling Power',
    aliases: ['Sterling'],
    logo: '/brands/sterling-power.webp',
  },
  {
    id: 'suzuki',
    name: 'Suzuki',
    aliases: ['Suzuki Marine'],
    logo: null,
  },
  {
    id: 'taylor-made',
    name: 'Taylor Made',
    aliases: [],
    logo: '/brands/taylor-made.svg',
  },
  {
    id: 'tecma',
    name: 'Tecma',
    aliases: [],
    logo: null,
  },
  {
    id: 'temo',
    name: 'TEMO',
    aliases: [],
    logo: '/brands/temo.svg',
  },
  {
    id: 'thetford',
    name: 'Thetford',
    aliases: [],
    logo: '/brands/thetford.png',
  },
  {
    id: 'tides-marine',
    name: 'Tides Marine',
    aliases: [],
    logo: '/brands/tides-marine.png',
  },
  {
    id: 'tohatsu',
    name: 'Tohatsu',
    aliases: ['Tohatsu Outboards'],
    logo: '/brands/tohatsu.png',
  },
  {
    id: 'torqeedo',
    name: 'Torqeedo',
    aliases: [],
    logo: '/brands/torqeedo.svg',
  },
  {
    id: 'trojan-battery',
    name: 'Trojan Battery',
    aliases: ['Trojan'],
    logo: '/brands/trojan-battery.svg',
  },
  {
    id: 'trudesign',
    name: 'TruDesign',
    aliases: ['Tru Design'],
    logo: '/brands/trudesign.png',
    whiteLogo: true,
  },
  {
    id: 'twin-disc',
    name: 'Twin Disc',
    aliases: [],
    logo: '/brands/twin-disc.png',
  },
  {
    id: 'ultra-marine',
    name: 'Ultra Marine',
    aliases: ['Ultra Anchor'],
    logo: '/brands/ultra-marine.png',
  },
  {
    id: 'uniden',
    name: 'Uniden',
    aliases: [],
    logo: '/brands/uniden.svg',
  },
  {
    id: 'vakaros',
    name: 'Vakaros',
    aliases: [],
    logo: null,
  },
  {
    id: 'veratron',
    name: 'Veratron',
    aliases: ['Veratron VDO'],
    logo: '/brands/veratron.webp',
    whiteLogo: true,
  },
  {
    id: 'vesper-marine',
    name: 'Vesper Marine',
    aliases: ['Vesper'],
    logo: null,
  },
  {
    id: 'vetus',
    name: 'Vetus',
    aliases: [],
    logo: '/brands/vetus.png',
  },
  {
    id: 'victron-energy',
    name: 'Victron Energy',
    aliases: ['Victron'],
    logo: '/brands/victron-energy.svg',
  },
  {
    id: 'viking',
    name: 'Viking',
    aliases: ['Viking Life-Saving Equipment'],
    logo: '/brands/viking.svg',
    inferFromName: false,
  },
  {
    id: 'vitrifrigo',
    name: 'Vitrifrigo',
    aliases: [],
    logo: null,
  },
  {
    id: 'volvo-penta',
    name: 'Volvo Penta',
    aliases: [],
    logo: '/brands/volvo-penta.svg',
  },
  {
    id: 'wallas',
    name: 'Wallas',
    aliases: [],
    logo: '/brands/wallas.png',
  },
  {
    id: 'webasto',
    name: 'Webasto',
    aliases: [],
    logo: '/brands/webasto.webp',
    whiteLogo: true,
  },
  {
    id: 'westerbeke',
    name: 'Westerbeke',
    aliases: [],
    logo: '/brands/westerbeke.gif',
  },
  {
    id: 'whale',
    name: 'Whale',
    aliases: ['Whale Pumps'],
    logo: '/brands/whale.svg',
    inferFromName: false,
  },
  {
    id: 'whisperpower',
    name: 'WhisperPower',
    aliases: ['Whisper Power'],
    logo: null,
  },
  {
    id: 'wichard',
    name: 'Wichard',
    aliases: [],
    logo: '/brands/wichard.svg',
    whiteLogo: true,
  },
  {
    id: 'xantrex',
    name: 'Xantrex',
    aliases: [],
    logo: '/brands/xantrex.png',
    whiteLogo: true,
  },
  {
    id: 'yacht-devices',
    name: 'Yacht Devices',
    aliases: [],
    logo: '/brands/yacht-devices.png',
  },
  {
    id: 'yamaha',
    name: 'Yamaha',
    aliases: ['Yamaha Marine'],
    logo: '/brands/yamaha.svg',
    whiteLogo: true,
  },
  {
    id: 'yanmar',
    name: 'Yanmar',
    aliases: ['Yanmar Marine'],
    logo: null,
  },
  {
    id: 'zf',
    name: 'ZF',
    aliases: ['ZF Marine'],
    logo: '/brands/zf.svg',
  },
  {
    id: 'zipwake',
    name: 'Zipwake',
    aliases: [],
    logo: '/brands/zipwake.svg',
    whiteLogo: true,
  },
  {
    id: 'zodiac',
    name: 'Zodiac',
    aliases: ['Zodiac Nautic'],
    logo: '/brands/zodiac.png',
  },
]
