import { describe, expect, it } from 'vitest'
import {
  AUTO_GENERATED_ENTRY_NOTE,
  isAutoGeneratedEntry,
  withHumanEditedFlag,
} from './instrument-data'

describe('auto-generated log entry flags', () => {
  it('detects auto-generated entries', () => {
    expect(isAutoGeneratedEntry({ autoGenerated: true })).toBe(true)
    expect(isAutoGeneratedEntry({ autoGenerated: false })).toBe(false)
    expect(isAutoGeneratedEntry(null)).toBe(false)
  })

  it('marks auto-generated entries as human-edited without dropping the auto flag', () => {
    expect(
      withHumanEditedFlag({
        autoGenerated: true,
        source: 'background-gps',
      }),
    ).toEqual({
      autoGenerated: true,
      source: 'background-gps',
      humanEdited: true,
    })
    expect(withHumanEditedFlag({ place: { name: 'Cowes' } })).toEqual({
      place: { name: 'Cowes' },
    })
    expect(AUTO_GENERATED_ENTRY_NOTE).toBe('Auto-tracked position')
  })
})
