/** Instrument readings attached to log entries (Signal K, BLE, etc.). */
export type SignKSnapshot = {
  observedAt: string
  latitude?: number | null
  longitude?: number | null
  headingTrue?: number | null
  windSpeedKnots?: number | null
  windDirectionTrue?: number | null
  depthMeters?: number | null
  waterTemperatureC?: number | null
  engineRpm?: number | null
  batteryVoltage?: number | null
  aisTargets?: Array<{
    mmsi?: string | null
    name?: string | null
    latitude?: number | null
    longitude?: number | null
  }> | null
  source?: string | null
}

export function isAutoGeneratedEntry(data: Record<string, unknown> | null | undefined) {
  return data?.autoGenerated === true
}

export function entryInstrumentData(
  data: Record<string, unknown> | null | undefined,
): SignKSnapshot | null {
  if (!data || typeof data.instruments !== 'object' || data.instruments == null) {
    return null
  }
  return data.instruments as SignKSnapshot
}
