import type { NotificationTopic } from '../../domain/notifications'
import type { InviteLocale } from '../../lib/invite-locale'
import { INVITE_LOCALE_CODES } from '../../lib/invite-locale'

export type ActivityActionStrings = {
  uploadedPhoto: string
  updatedPhoto: string
  deletedPhoto: string
  addedDocumentCategory: string
  uploadedDocument: string
  addedDocumentLink: string
  updatedDocument: string
  deletedDocument: string
  addedAsset: string
  updatedAsset: string
  removedAsset: string
  loggedWorkOnAsset: string
  sentMemberInvite: string
  addedMember: string
  createdMemberInviteLink: string
  changedMemberRole: string
  removedMember: string
  joinedOrg: string
  addedContact: string
  updatedContact: string
  removedContact: string
  updatedShareStructure: string
  updatedShareLabel: string
  assignedShareOwner: string
  removedShareOwner: string
  attachedBoat: string
}

export type ActivityNotificationStrings = {
  someone: string
  sectionFallback: string
  resourceSectionTitle: string
  resourceSectionBody: string
  sectionByTopic: Partial<Record<NotificationTopic, string>>
  tripCompletedTitle: string
  tripCompletedBody: string
  adminJobCompletedTitle: string
  adminJobFailedTitle: string
  adminJobBody: string
  chatNewMessageTitle: string
  chatNewMessageBody: string
  actions: ActivityActionStrings
}

const EN: ActivityNotificationStrings = {
  someone: 'Someone',
  sectionFallback: 'updates',
  resourceSectionTitle: '{resourceName}: {section}',
  resourceSectionBody: '{actor} {action}',
  sectionByTopic: {
    BOAT_PHOTOS: 'photos updated',
    BOAT_DOCUMENTS: 'documents updated',
    BOAT_ASSETS: 'assets updated',
    BOAT_MEMBERS: 'members updated',
    BOAT_CONTACTS: 'contacts updated',
    BOAT_SHARES: 'shares updated',
    ORG_MEMBERS: 'members updated',
    ORG_DOCUMENTS: 'documents updated',
    ORG_CONTACTS: 'contacts updated',
    ORG_BOATS: 'boats updated',
  },
  tripCompletedTitle: '{boatName}: trip completed',
  tripCompletedBody: '{tripTitle} was marked complete.',
  adminJobCompletedTitle: 'Background job completed',
  adminJobFailedTitle: 'Background job failed',
  adminJobBody: '{queueName} ({jobId}): {summary}',
  chatNewMessageTitle: 'New message',
  chatNewMessageBody: 'You have a new message in Logmaster.',
  actions: {
    uploadedPhoto: 'uploaded a photo.',
    updatedPhoto: 'updated a photo.',
    deletedPhoto: 'deleted a photo.',
    addedDocumentCategory: 'added a document category.',
    uploadedDocument: 'uploaded a document.',
    addedDocumentLink: 'added a document link.',
    updatedDocument: 'updated a document.',
    deletedDocument: 'deleted a document.',
    addedAsset: 'added asset “{name}”.',
    updatedAsset: 'updated asset “{name}”.',
    removedAsset: 'removed asset “{name}”.',
    loggedWorkOnAsset: 'logged work on asset “{name}”.',
    sentMemberInvite: 'sent a member invite.',
    addedMember: 'added a member.',
    createdMemberInviteLink: 'created a member invite link.',
    changedMemberRole: 'changed a member role.',
    removedMember: 'removed a member.',
    joinedOrg: 'joined the org.',
    addedContact: 'added contact “{name}”.',
    updatedContact: 'updated a contact.',
    removedContact: 'removed a contact.',
    updatedShareStructure: 'updated share structure.',
    updatedShareLabel: 'updated a share label.',
    assignedShareOwner: 'assigned a share owner.',
    removedShareOwner: 'removed a share owner.',
    attachedBoat: 'attached boat “{name}”.',
  },
}

function mergeStrings(
  base: ActivityNotificationStrings,
  patch: Partial<ActivityNotificationStrings> & {
    actions?: Partial<ActivityActionStrings>
    sectionByTopic?: Partial<Record<NotificationTopic, string>>
  },
): ActivityNotificationStrings {
  return {
    ...base,
    ...patch,
    sectionByTopic: { ...base.sectionByTopic, ...patch.sectionByTopic },
    actions: { ...base.actions, ...patch.actions },
  }
}

const SV = mergeStrings(EN, {
  someone: 'Någon',
  sectionFallback: 'uppdateringar',
  resourceSectionTitle: '{resourceName}: {section}',
  resourceSectionBody: '{actor} {action}',
  sectionByTopic: {
    BOAT_PHOTOS: 'foton uppdaterade',
    BOAT_DOCUMENTS: 'dokument uppdaterade',
    BOAT_ASSETS: 'tillgångar uppdaterade',
    BOAT_MEMBERS: 'medlemmar uppdaterade',
    BOAT_CONTACTS: 'kontakter uppdaterade',
    BOAT_SHARES: 'andelar uppdaterade',
    ORG_MEMBERS: 'medlemmar uppdaterade',
    ORG_DOCUMENTS: 'dokument uppdaterade',
    ORG_CONTACTS: 'kontakter uppdaterade',
    ORG_BOATS: 'båtar uppdaterade',
  },
  tripCompletedTitle: '{boatName}: tur avslutad',
  tripCompletedBody: '{tripTitle} markerades som avslutad.',
  adminJobCompletedTitle: 'Bakgrundsjobb slutfört',
  adminJobFailedTitle: 'Bakgrundsjobb misslyckades',
  chatNewMessageTitle: 'Nytt meddelande',
  chatNewMessageBody: 'Du har ett nytt meddelande i Logmaster.',
  actions: {
    uploadedPhoto: 'laddade upp ett foto.',
    updatedPhoto: 'uppdaterade ett foto.',
    deletedPhoto: 'tog bort ett foto.',
    addedDocumentCategory: 'lade till en dokumentkategori.',
    uploadedDocument: 'laddade upp ett dokument.',
    addedDocumentLink: 'lade till en dokumentlänk.',
    updatedDocument: 'uppdaterade ett dokument.',
    deletedDocument: 'tog bort ett dokument.',
    addedAsset: 'lade till tillgången ”{name}”.',
    updatedAsset: 'uppdaterade tillgången ”{name}”.',
    removedAsset: 'tog bort tillgången ”{name}”.',
    loggedWorkOnAsset: 'loggade arbete på tillgången ”{name}”.',
    sentMemberInvite: 'skickade en medlemsinbjudan.',
    addedMember: 'lade till en medlem.',
    createdMemberInviteLink: 'skapade en inbjudningslänk.',
    changedMemberRole: 'ändrade en medlemsroll.',
    removedMember: 'tog bort en medlem.',
    joinedOrg: 'gick med i organisationen.',
    addedContact: 'lade till kontakten ”{name}”.',
    updatedContact: 'uppdaterade en kontakt.',
    removedContact: 'tog bort en kontakt.',
    updatedShareStructure: 'uppdaterade andelsstrukturen.',
    updatedShareLabel: 'uppdaterade en andelsetikett.',
    assignedShareOwner: 'tilldelade en ägare.',
    removedShareOwner: 'tog bort en ägare.',
    attachedBoat: 'kopplade båten ”{name}”.',
  },
})

const DE = mergeStrings(EN, {
  someone: 'Jemand',
  sectionFallback: 'Aktualisierungen',
  tripCompletedTitle: '{boatName}: Törn abgeschlossen',
  tripCompletedBody: '{tripTitle} wurde als abgeschlossen markiert.',
  adminJobCompletedTitle: 'Hintergrundjob abgeschlossen',
  adminJobFailedTitle: 'Hintergrundjob fehlgeschlagen',
  chatNewMessageTitle: 'Neue Nachricht',
  chatNewMessageBody: 'Du hast eine neue Nachricht in Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'Fotos aktualisiert',
    BOAT_DOCUMENTS: 'Dokumente aktualisiert',
    BOAT_ASSETS: 'Ausrüstung aktualisiert',
    BOAT_MEMBERS: 'Mitglieder aktualisiert',
    BOAT_CONTACTS: 'Kontakte aktualisiert',
    BOAT_SHARES: 'Anteile aktualisiert',
    ORG_MEMBERS: 'Mitglieder aktualisiert',
    ORG_DOCUMENTS: 'Dokumente aktualisiert',
    ORG_CONTACTS: 'Kontakte aktualisiert',
    ORG_BOATS: 'Boote aktualisiert',
  },
  actions: {
    uploadedPhoto: 'hat ein Foto hochgeladen.',
    updatedPhoto: 'hat ein Foto aktualisiert.',
    deletedPhoto: 'hat ein Foto gelöscht.',
    addedDocumentCategory: 'hat eine Dokumentkategorie hinzugefügt.',
    uploadedDocument: 'hat ein Dokument hochgeladen.',
    addedDocumentLink: 'hat einen Dokumentlink hinzugefügt.',
    updatedDocument: 'hat ein Dokument aktualisiert.',
    deletedDocument: 'hat ein Dokument gelöscht.',
    addedAsset: 'hat die Ausrüstung „{name}“ hinzugefügt.',
    updatedAsset: 'hat die Ausrüstung „{name}“ aktualisiert.',
    removedAsset: 'hat die Ausrüstung „{name}“ entfernt.',
    loggedWorkOnAsset: 'hat Arbeit an „{name}“ protokolliert.',
    sentMemberInvite: 'hat eine Mitglieder-Einladung gesendet.',
    addedMember: 'hat ein Mitglied hinzugefügt.',
    createdMemberInviteLink: 'hat einen Einladungslink erstellt.',
    changedMemberRole: 'hat eine Mitgliederrolle geändert.',
    removedMember: 'hat ein Mitglied entfernt.',
    joinedOrg: 'ist der Organisation beigetreten.',
    addedContact: 'hat den Kontakt „{name}“ hinzugefügt.',
    updatedContact: 'hat einen Kontakt aktualisiert.',
    removedContact: 'hat einen Kontakt entfernt.',
    updatedShareStructure: 'hat die Anteilsstruktur aktualisiert.',
    updatedShareLabel: 'hat eine Anteilsetikette aktualisiert.',
    assignedShareOwner: 'hat einen Eigentümer zugewiesen.',
    removedShareOwner: 'hat einen Eigentümer entfernt.',
    attachedBoat: 'hat das Boot „{name}“ verknüpft.',
  },
})

const FR = mergeStrings(EN, {
  someone: 'Quelqu’un',
  sectionFallback: 'mises à jour',
  tripCompletedTitle: '{boatName} : sortie terminée',
  tripCompletedBody: '{tripTitle} a été marquée comme terminée.',
  adminJobCompletedTitle: 'Tâche de fond terminée',
  adminJobFailedTitle: 'Échec de la tâche de fond',
  chatNewMessageTitle: 'Nouveau message',
  chatNewMessageBody: 'Vous avez un nouveau message dans Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'photos mises à jour',
    BOAT_DOCUMENTS: 'documents mis à jour',
    BOAT_ASSETS: 'équipements mis à jour',
    BOAT_MEMBERS: 'membres mis à jour',
    BOAT_CONTACTS: 'contacts mis à jour',
    BOAT_SHARES: 'parts mises à jour',
    ORG_MEMBERS: 'membres mis à jour',
    ORG_DOCUMENTS: 'documents mis à jour',
    ORG_CONTACTS: 'contacts mis à jour',
    ORG_BOATS: 'bateaux mis à jour',
  },
  actions: {
    uploadedPhoto: 'a ajouté une photo.',
    updatedPhoto: 'a mis à jour une photo.',
    deletedPhoto: 'a supprimé une photo.',
    addedDocumentCategory: 'a ajouté une catégorie de documents.',
    uploadedDocument: 'a téléversé un document.',
    addedDocumentLink: 'a ajouté un lien de document.',
    updatedDocument: 'a mis à jour un document.',
    deletedDocument: 'a supprimé un document.',
    addedAsset: 'a ajouté l’équipement « {name} ».',
    updatedAsset: 'a mis à jour l’équipement « {name} ».',
    removedAsset: 'a retiré l’équipement « {name} ».',
    loggedWorkOnAsset: 'a enregistré du travail sur « {name} ».',
    sentMemberInvite: 'a envoyé une invitation de membre.',
    addedMember: 'a ajouté un membre.',
    createdMemberInviteLink: 'a créé un lien d’invitation.',
    changedMemberRole: 'a modifié le rôle d’un membre.',
    removedMember: 'a retiré un membre.',
    joinedOrg: 'a rejoint l’organisation.',
    addedContact: 'a ajouté le contact « {name} ».',
    updatedContact: 'a mis à jour un contact.',
    removedContact: 'a retiré un contact.',
    updatedShareStructure: 'a mis à jour la structure des parts.',
    updatedShareLabel: 'a mis à jour une étiquette de part.',
    assignedShareOwner: 'a assigné un propriétaire.',
    removedShareOwner: 'a retiré un propriétaire.',
    attachedBoat: 'a rattaché le bateau « {name} ».',
  },
})

const ES = mergeStrings(EN, {
  someone: 'Alguien',
  sectionFallback: 'actualizaciones',
  tripCompletedTitle: '{boatName}: travesía completada',
  tripCompletedBody: '{tripTitle} se marcó como completada.',
  adminJobCompletedTitle: 'Tarea en segundo plano completada',
  adminJobFailedTitle: 'Tarea en segundo plano fallida',
  chatNewMessageTitle: 'Nuevo mensaje',
  chatNewMessageBody: 'Tienes un nuevo mensaje en Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'fotos actualizadas',
    BOAT_DOCUMENTS: 'documentos actualizados',
    BOAT_ASSETS: 'activos actualizados',
    BOAT_MEMBERS: 'miembros actualizados',
    BOAT_CONTACTS: 'contactos actualizados',
    BOAT_SHARES: 'participaciones actualizadas',
    ORG_MEMBERS: 'miembros actualizados',
    ORG_DOCUMENTS: 'documentos actualizados',
    ORG_CONTACTS: 'contactos actualizados',
    ORG_BOATS: 'barcos actualizados',
  },
  actions: {
    uploadedPhoto: 'subió una foto.',
    updatedPhoto: 'actualizó una foto.',
    deletedPhoto: 'eliminó una foto.',
    addedDocumentCategory: 'añadió una categoría de documentos.',
    uploadedDocument: 'subió un documento.',
    addedDocumentLink: 'añadió un enlace de documento.',
    updatedDocument: 'actualizó un documento.',
    deletedDocument: 'eliminó un documento.',
    addedAsset: 'añadió el activo «{name}».',
    updatedAsset: 'actualizó el activo «{name}».',
    removedAsset: 'eliminó el activo «{name}».',
    loggedWorkOnAsset: 'registró trabajo en «{name}».',
    sentMemberInvite: 'envió una invitación de miembro.',
    addedMember: 'añadió un miembro.',
    createdMemberInviteLink: 'creó un enlace de invitación.',
    changedMemberRole: 'cambió el rol de un miembro.',
    removedMember: 'eliminó un miembro.',
    joinedOrg: 'se unió a la organización.',
    addedContact: 'añadió el contacto «{name}».',
    updatedContact: 'actualizó un contacto.',
    removedContact: 'eliminó un contacto.',
    updatedShareStructure: 'actualizó la estructura de participaciones.',
    updatedShareLabel: 'actualizó una etiqueta de participación.',
    assignedShareOwner: 'asignó un propietario.',
    removedShareOwner: 'eliminó un propietario.',
    attachedBoat: 'vinculó el barco «{name}».',
  },
})

const DA = mergeStrings(EN, {
  someone: 'Nogen',
  sectionFallback: 'opdateringer',
  tripCompletedTitle: '{boatName}: tur afsluttet',
  tripCompletedBody: '{tripTitle} blev markeret som afsluttet.',
  adminJobCompletedTitle: 'Baggrundsjob fuldført',
  adminJobFailedTitle: 'Baggrundsjob mislykkedes',
  chatNewMessageTitle: 'Ny besked',
  chatNewMessageBody: 'Du har en ny besked i Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'fotos opdateret',
    BOAT_DOCUMENTS: 'dokumenter opdateret',
    BOAT_ASSETS: 'aktiver opdateret',
    BOAT_MEMBERS: 'medlemmer opdateret',
    BOAT_CONTACTS: 'kontakter opdateret',
    BOAT_SHARES: 'andele opdateret',
    ORG_MEMBERS: 'medlemmer opdateret',
    ORG_DOCUMENTS: 'dokumenter opdateret',
    ORG_CONTACTS: 'kontakter opdateret',
    ORG_BOATS: 'både opdateret',
  },
  actions: {
    uploadedPhoto: 'uploadede et foto.',
    updatedPhoto: 'opdaterede et foto.',
    deletedPhoto: 'slettede et foto.',
    addedDocumentCategory: 'tilføjede en dokumentkategori.',
    uploadedDocument: 'uploadede et dokument.',
    addedDocumentLink: 'tilføjede et dokumentlink.',
    updatedDocument: 'opdaterede et dokument.',
    deletedDocument: 'slettede et dokument.',
    addedAsset: 'tilføjede aktivet ”{name}”.',
    updatedAsset: 'opdaterede aktivet ”{name}”.',
    removedAsset: 'fjernede aktivet ”{name}”.',
    loggedWorkOnAsset: 'registrerede arbejde på aktivet ”{name}”.',
    sentMemberInvite: 'sendte en medlemsinvitation.',
    addedMember: 'tilføjede et medlem.',
    createdMemberInviteLink: 'oprettede et invitationslink.',
    changedMemberRole: 'ændrede en medlemsrolle.',
    removedMember: 'fjernede et medlem.',
    joinedOrg: 'tilsluttede sig organisationen.',
    addedContact: 'tilføjede kontakten ”{name}”.',
    updatedContact: 'opdaterede en kontakt.',
    removedContact: 'fjernede en kontakt.',
    updatedShareStructure: 'opdaterede andelsstrukturen.',
    updatedShareLabel: 'opdaterede en andelsbetegnelse.',
    assignedShareOwner: 'tildelte en ejer.',
    removedShareOwner: 'fjernede en ejer.',
    attachedBoat: 'tilknyttede båden ”{name}”.',
  },
})

const NL = mergeStrings(EN, {
  someone: 'Iemand',
  sectionFallback: 'updates',
  tripCompletedTitle: '{boatName}: tocht voltooid',
  tripCompletedBody: '{tripTitle} is als voltooid gemarkeerd.',
  adminJobCompletedTitle: 'Achtergrondtaak voltooid',
  adminJobFailedTitle: 'Achtergrondtaak mislukt',
  chatNewMessageTitle: 'Nieuw bericht',
  chatNewMessageBody: 'Je hebt een nieuw bericht in Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'foto’s bijgewerkt',
    BOAT_DOCUMENTS: 'documenten bijgewerkt',
    BOAT_ASSETS: 'assets bijgewerkt',
    BOAT_MEMBERS: 'leden bijgewerkt',
    BOAT_CONTACTS: 'contacten bijgewerkt',
    BOAT_SHARES: 'aandelen bijgewerkt',
    ORG_MEMBERS: 'leden bijgewerkt',
    ORG_DOCUMENTS: 'documenten bijgewerkt',
    ORG_CONTACTS: 'contacten bijgewerkt',
    ORG_BOATS: 'boten bijgewerkt',
  },
  actions: {
    uploadedPhoto: 'heeft een foto geüpload.',
    updatedPhoto: 'heeft een foto bijgewerkt.',
    deletedPhoto: 'heeft een foto verwijderd.',
    addedDocumentCategory: 'heeft een documentcategorie toegevoegd.',
    uploadedDocument: 'heeft een document geüpload.',
    addedDocumentLink: 'heeft een documentlink toegevoegd.',
    updatedDocument: 'heeft een document bijgewerkt.',
    deletedDocument: 'heeft een document verwijderd.',
    addedAsset: 'heeft asset “{name}” toegevoegd.',
    updatedAsset: 'heeft asset “{name}” bijgewerkt.',
    removedAsset: 'heeft asset “{name}” verwijderd.',
    loggedWorkOnAsset: 'heeft werk geregistreerd op “{name}”.',
    sentMemberInvite: 'heeft een liduitnodiging verstuurd.',
    addedMember: 'heeft een lid toegevoegd.',
    createdMemberInviteLink: 'heeft een uitnodigingslink gemaakt.',
    changedMemberRole: 'heeft een lidrol gewijzigd.',
    removedMember: 'heeft een lid verwijderd.',
    joinedOrg: 'is toegetreden tot de organisatie.',
    addedContact: 'heeft contact “{name}” toegevoegd.',
    updatedContact: 'heeft een contact bijgewerkt.',
    removedContact: 'heeft een contact verwijderd.',
    updatedShareStructure: 'heeft de aandelenstructuur bijgewerkt.',
    updatedShareLabel: 'heeft een aandelenlabel bijgewerkt.',
    assignedShareOwner: 'heeft een eigenaar toegewezen.',
    removedShareOwner: 'heeft een eigenaar verwijderd.',
    attachedBoat: 'heeft boot “{name}” gekoppeld.',
  },
})

const PT = mergeStrings(EN, {
  someone: 'Alguém',
  sectionFallback: 'atualizações',
  tripCompletedTitle: '{boatName}: viagem concluída',
  tripCompletedBody: '{tripTitle} foi marcada como concluída.',
  adminJobCompletedTitle: 'Tarefa em segundo plano concluída',
  adminJobFailedTitle: 'Tarefa em segundo plano falhou',
  chatNewMessageTitle: 'Nova mensagem',
  chatNewMessageBody: 'Tem uma nova mensagem no Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'fotos atualizadas',
    BOAT_DOCUMENTS: 'documentos atualizados',
    BOAT_ASSETS: 'ativos atualizados',
    BOAT_MEMBERS: 'membros atualizados',
    BOAT_CONTACTS: 'contactos atualizados',
    BOAT_SHARES: 'participações atualizadas',
    ORG_MEMBERS: 'membros atualizados',
    ORG_DOCUMENTS: 'documentos atualizados',
    ORG_CONTACTS: 'contactos atualizados',
    ORG_BOATS: 'barcos atualizados',
  },
  actions: {
    uploadedPhoto: 'carregou uma foto.',
    updatedPhoto: 'atualizou uma foto.',
    deletedPhoto: 'eliminou uma foto.',
    addedDocumentCategory: 'adicionou uma categoria de documentos.',
    uploadedDocument: 'carregou um documento.',
    addedDocumentLink: 'adicionou uma ligação de documento.',
    updatedDocument: 'atualizou um documento.',
    deletedDocument: 'eliminou um documento.',
    addedAsset: 'adicionou o ativo “{name}”.',
    updatedAsset: 'atualizou o ativo “{name}”.',
    removedAsset: 'removeu o ativo “{name}”.',
    loggedWorkOnAsset: 'registou trabalho no ativo “{name}”.',
    sentMemberInvite: 'enviou um convite de membro.',
    addedMember: 'adicionou um membro.',
    createdMemberInviteLink: 'criou uma ligação de convite.',
    changedMemberRole: 'alterou a função de um membro.',
    removedMember: 'removeu um membro.',
    joinedOrg: 'entrou na organização.',
    addedContact: 'adicionou o contacto “{name}”.',
    updatedContact: 'atualizou um contacto.',
    removedContact: 'removeu um contacto.',
    updatedShareStructure: 'atualizou a estrutura de participações.',
    updatedShareLabel: 'atualizou uma etiqueta de participação.',
    assignedShareOwner: 'atribuiu um proprietário.',
    removedShareOwner: 'removeu um proprietário.',
    attachedBoat: 'associou o barco “{name}”.',
  },
})

const FI = mergeStrings(EN, {
  someone: 'Joku',
  sectionFallback: 'päivitykset',
  tripCompletedTitle: '{boatName}: matka valmis',
  tripCompletedBody: '{tripTitle} merkittiin valmiiksi.',
  adminJobCompletedTitle: 'Taustatyö valmis',
  adminJobFailedTitle: 'Taustatyö epäonnistui',
  chatNewMessageTitle: 'Uusi viesti',
  chatNewMessageBody: 'Sinulla on uusi viesti Logmasterissa.',
  sectionByTopic: {
    BOAT_PHOTOS: 'kuvat päivitetty',
    BOAT_DOCUMENTS: 'asiakirjat päivitetty',
    BOAT_ASSETS: 'varusteet päivitetty',
    BOAT_MEMBERS: 'jäsenet päivitetty',
    BOAT_CONTACTS: 'yhteystiedot päivitetty',
    BOAT_SHARES: 'osuudet päivitetty',
    ORG_MEMBERS: 'jäsenet päivitetty',
    ORG_DOCUMENTS: 'asiakirjat päivitetty',
    ORG_CONTACTS: 'yhteystiedot päivitetty',
    ORG_BOATS: 'veneet päivitetty',
  },
  actions: {
    uploadedPhoto: 'latasi kuvan.',
    updatedPhoto: 'päivitti kuvan.',
    deletedPhoto: 'poisti kuvan.',
    addedDocumentCategory: 'lisäsi asiakirjakategorian.',
    uploadedDocument: 'latasi asiakirjan.',
    addedDocumentLink: 'lisäsi asiakirjalinkin.',
    updatedDocument: 'päivitti asiakirjan.',
    deletedDocument: 'poisti asiakirjan.',
    addedAsset: 'lisäsi varusteen ”{name}”.',
    updatedAsset: 'päivitti varusteen ”{name}”.',
    removedAsset: 'poisti varusteen ”{name}”.',
    loggedWorkOnAsset: 'kirjasi työtä varusteella ”{name}”.',
    sentMemberInvite: 'lähetti jäsenkutsun.',
    addedMember: 'lisäsi jäsenen.',
    createdMemberInviteLink: 'loi kutsulinkin.',
    changedMemberRole: 'muutti jäsenen roolia.',
    removedMember: 'poisti jäsenen.',
    joinedOrg: 'liittyi organisaatioon.',
    addedContact: 'lisäsi yhteystiedon ”{name}”.',
    updatedContact: 'päivitti yhteystiedon.',
    removedContact: 'poisti yhteystiedon.',
    updatedShareStructure: 'päivitti osuusrakenteen.',
    updatedShareLabel: 'päivitti osuusmerkinnän.',
    assignedShareOwner: 'määräsi omistajan.',
    removedShareOwner: 'poisti omistajan.',
    attachedBoat: 'liitti veneen ”{name}”.',
  },
})

const EL = mergeStrings(EN, {
  someone: 'Κάποιος',
  sectionFallback: 'ενημερώσεις',
  tripCompletedTitle: '{boatName}: ολοκληρωμένο ταξίδι',
  tripCompletedBody: 'Το {tripTitle} σημειώθηκε ως ολοκληρωμένο.',
  adminJobCompletedTitle: 'Ολοκληρώθηκε εργασία παρασκηνίου',
  adminJobFailedTitle: 'Απέτυχε εργασία παρασκηνίου',
  chatNewMessageTitle: 'Νέο μήνυμα',
  chatNewMessageBody: 'Έχετε νέο μήνυμα στο Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'φωτογραφίες ενημερώθηκαν',
    BOAT_DOCUMENTS: 'έγγραφα ενημερώθηκαν',
    BOAT_ASSETS: 'εξοπλισμός ενημερώθηκε',
    BOAT_MEMBERS: 'μέλη ενημερώθηκαν',
    BOAT_CONTACTS: 'επαφές ενημερώθηκαν',
    BOAT_SHARES: 'μετοχές ενημερώθηκαν',
    ORG_MEMBERS: 'μέλη ενημερώθηκαν',
    ORG_DOCUMENTS: 'έγγραφα ενημερώθηκαν',
    ORG_CONTACTS: 'επαφές ενημερώθηκαν',
    ORG_BOATS: 'σκάφη ενημερώθηκαν',
  },
  actions: {
    uploadedPhoto: 'ανέβασε μια φωτογραφία.',
    updatedPhoto: 'ενημέρωσε μια φωτογραφία.',
    deletedPhoto: 'διέγραψε μια φωτογραφία.',
    addedDocumentCategory: 'πρόσθεσε κατηγορία εγγράφων.',
    uploadedDocument: 'ανέβασε ένα έγγραφο.',
    addedDocumentLink: 'πρόσθεσε σύνδεσμο εγγράφου.',
    updatedDocument: 'ενημέρωσε ένα έγγραφο.',
    deletedDocument: 'διέγραψε ένα έγγραφο.',
    addedAsset: 'πρόσθεσε τον εξοπλισμό «{name}».',
    updatedAsset: 'ενημέρωσε τον εξοπλισμό «{name}».',
    removedAsset: 'αφαίρεσε τον εξοπλισμό «{name}».',
    loggedWorkOnAsset: 'κατέγραψε εργασία στον «{name}».',
    sentMemberInvite: 'έστειλε πρόσκληση μέλους.',
    addedMember: 'πρόσθεσε μέλος.',
    createdMemberInviteLink: 'δημιούργησε σύνδεσμο πρόσκλησης.',
    changedMemberRole: 'άλλαξε ρόλο μέλους.',
    removedMember: 'αφαίρεσε μέλος.',
    joinedOrg: 'έγινε μέλος του οργανισμού.',
    addedContact: 'πρόσθεσε την επαφή «{name}».',
    updatedContact: 'ενημέρωσε επαφή.',
    removedContact: 'αφαίρεσε επαφή.',
    updatedShareStructure: 'ενημέρωσε τη δομή μετοχών.',
    updatedShareLabel: 'ενημέρωσε ετικέτα μετοχής.',
    assignedShareOwner: 'ανέθεσε ιδιοκτήτη.',
    removedShareOwner: 'αφαίρεσε ιδιοκτήτη.',
    attachedBoat: 'σύνδεσε το σκάφος «{name}».',
  },
})

const TR = mergeStrings(EN, {
  someone: 'Birisi',
  sectionFallback: 'güncellemeler',
  tripCompletedTitle: '{boatName}: sefer tamamlandı',
  tripCompletedBody: '{tripTitle} tamamlandı olarak işaretlendi.',
  adminJobCompletedTitle: 'Arka plan görevi tamamlandı',
  adminJobFailedTitle: 'Arka plan görevi başarısız',
  chatNewMessageTitle: 'Yeni mesaj',
  chatNewMessageBody: 'Logmaster’da yeni bir mesajınız var.',
  sectionByTopic: {
    BOAT_PHOTOS: 'fotoğraflar güncellendi',
    BOAT_DOCUMENTS: 'belgeler güncellendi',
    BOAT_ASSETS: 'varlıklar güncellendi',
    BOAT_MEMBERS: 'üyeler güncellendi',
    BOAT_CONTACTS: 'kişiler güncellendi',
    BOAT_SHARES: 'hisseler güncellendi',
    ORG_MEMBERS: 'üyeler güncellendi',
    ORG_DOCUMENTS: 'belgeler güncellendi',
    ORG_CONTACTS: 'kişiler güncellendi',
    ORG_BOATS: 'tekneler güncellendi',
  },
  actions: {
    uploadedPhoto: 'bir fotoğraf yükledi.',
    updatedPhoto: 'bir fotoğrafı güncelledi.',
    deletedPhoto: 'bir fotoğrafı sildi.',
    addedDocumentCategory: 'bir belge kategorisi ekledi.',
    uploadedDocument: 'bir belge yükledi.',
    addedDocumentLink: 'bir belge bağlantısı ekledi.',
    updatedDocument: 'bir belgeyi güncelledi.',
    deletedDocument: 'bir belgeyi sildi.',
    addedAsset: '“{name}” varlığını ekledi.',
    updatedAsset: '“{name}” varlığını güncelledi.',
    removedAsset: '“{name}” varlığını kaldırdı.',
    loggedWorkOnAsset: '“{name}” üzerinde çalışma kaydetti.',
    sentMemberInvite: 'bir üye daveti gönderdi.',
    addedMember: 'bir üye ekledi.',
    createdMemberInviteLink: 'bir davet bağlantısı oluşturdu.',
    changedMemberRole: 'bir üye rolünü değiştirdi.',
    removedMember: 'bir üyeyi kaldırdı.',
    joinedOrg: 'organizasyona katıldı.',
    addedContact: '“{name}” kişisini ekledi.',
    updatedContact: 'bir kişiyi güncelledi.',
    removedContact: 'bir kişiyi kaldırdı.',
    updatedShareStructure: 'hisse yapısını güncelledi.',
    updatedShareLabel: 'bir hisse etiketini güncelledi.',
    assignedShareOwner: 'bir sahip atadı.',
    removedShareOwner: 'bir sahibi kaldırdı.',
    attachedBoat: '“{name}” teknesini bağladı.',
  },
})

const VI = mergeStrings(EN, {
  someone: 'Ai đó',
  sectionFallback: 'cập nhật',
  tripCompletedTitle: '{boatName}: chuyến đi hoàn thành',
  tripCompletedBody: '{tripTitle} đã được đánh dấu hoàn thành.',
  adminJobCompletedTitle: 'Tác vụ nền đã hoàn thành',
  adminJobFailedTitle: 'Tác vụ nền thất bại',
  chatNewMessageTitle: 'Tin nhắn mới',
  chatNewMessageBody: 'Bạn có tin nhắn mới trong Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'ảnh đã cập nhật',
    BOAT_DOCUMENTS: 'tài liệu đã cập nhật',
    BOAT_ASSETS: 'tài sản đã cập nhật',
    BOAT_MEMBERS: 'thành viên đã cập nhật',
    BOAT_CONTACTS: 'liên hệ đã cập nhật',
    BOAT_SHARES: 'cổ phần đã cập nhật',
    ORG_MEMBERS: 'thành viên đã cập nhật',
    ORG_DOCUMENTS: 'tài liệu đã cập nhật',
    ORG_CONTACTS: 'liên hệ đã cập nhật',
    ORG_BOATS: 'thuyền đã cập nhật',
  },
  actions: {
    uploadedPhoto: 'đã tải lên một ảnh.',
    updatedPhoto: 'đã cập nhật một ảnh.',
    deletedPhoto: 'đã xóa một ảnh.',
    addedDocumentCategory: 'đã thêm danh mục tài liệu.',
    uploadedDocument: 'đã tải lên một tài liệu.',
    addedDocumentLink: 'đã thêm liên kết tài liệu.',
    updatedDocument: 'đã cập nhật một tài liệu.',
    deletedDocument: 'đã xóa một tài liệu.',
    addedAsset: 'đã thêm tài sản “{name}”.',
    updatedAsset: 'đã cập nhật tài sản “{name}”.',
    removedAsset: 'đã xóa tài sản “{name}”.',
    loggedWorkOnAsset: 'đã ghi công việc trên “{name}”.',
    sentMemberInvite: 'đã gửi lời mời thành viên.',
    addedMember: 'đã thêm thành viên.',
    createdMemberInviteLink: 'đã tạo liên kết mời.',
    changedMemberRole: 'đã đổi vai trò thành viên.',
    removedMember: 'đã xóa thành viên.',
    joinedOrg: 'đã tham gia tổ chức.',
    addedContact: 'đã thêm liên hệ “{name}”.',
    updatedContact: 'đã cập nhật liên hệ.',
    removedContact: 'đã xóa liên hệ.',
    updatedShareStructure: 'đã cập nhật cấu trúc cổ phần.',
    updatedShareLabel: 'đã cập nhật nhãn cổ phần.',
    assignedShareOwner: 'đã gán chủ sở hữu.',
    removedShareOwner: 'đã xóa chủ sở hữu.',
    attachedBoat: 'đã gắn thuyền “{name}”.',
  },
})

const JA = mergeStrings(EN, {
  someone: '誰か',
  sectionFallback: '更新',
  resourceSectionBody: '{actor}{action}',
  tripCompletedTitle: '{boatName}：トリップ完了',
  tripCompletedBody: '{tripTitle} が完了としてマークされました。',
  adminJobCompletedTitle: 'バックグラウンドジョブ完了',
  adminJobFailedTitle: 'バックグラウンドジョブ失敗',
  chatNewMessageTitle: '新しいメッセージ',
  chatNewMessageBody: 'Logmaster に新しいメッセージがあります。',
  sectionByTopic: {
    BOAT_PHOTOS: '写真を更新',
    BOAT_DOCUMENTS: 'ドキュメントを更新',
    BOAT_ASSETS: '資産を更新',
    BOAT_MEMBERS: 'メンバーを更新',
    BOAT_CONTACTS: '連絡先を更新',
    BOAT_SHARES: 'シェアを更新',
    ORG_MEMBERS: 'メンバーを更新',
    ORG_DOCUMENTS: 'ドキュメントを更新',
    ORG_CONTACTS: '連絡先を更新',
    ORG_BOATS: 'ボートを更新',
  },
  actions: {
    uploadedPhoto: 'さんが写真をアップロードしました。',
    updatedPhoto: 'さんが写真を更新しました。',
    deletedPhoto: 'さんが写真を削除しました。',
    addedDocumentCategory: 'さんがドキュメントカテゴリを追加しました。',
    uploadedDocument: 'さんがドキュメントをアップロードしました。',
    addedDocumentLink: 'さんがドキュメントリンクを追加しました。',
    updatedDocument: 'さんがドキュメントを更新しました。',
    deletedDocument: 'さんがドキュメントを削除しました。',
    addedAsset: 'さんが資産「{name}」を追加しました。',
    updatedAsset: 'さんが資産「{name}」を更新しました。',
    removedAsset: 'さんが資産「{name}」を削除しました。',
    loggedWorkOnAsset: 'さんが資産「{name}」の作業を記録しました。',
    sentMemberInvite: 'さんがメンバー招待を送信しました。',
    addedMember: 'さんがメンバーを追加しました。',
    createdMemberInviteLink: 'さんが招待リンクを作成しました。',
    changedMemberRole: 'さんがメンバーの役割を変更しました。',
    removedMember: 'さんがメンバーを削除しました。',
    joinedOrg: 'さんが組織に参加しました。',
    addedContact: 'さんが連絡先「{name}」を追加しました。',
    updatedContact: 'さんが連絡先を更新しました。',
    removedContact: 'さんが連絡先を削除しました。',
    updatedShareStructure: 'さんがシェア構成を更新しました。',
    updatedShareLabel: 'さんがシェアラベルを更新しました。',
    assignedShareOwner: 'さんがオーナーを割り当てました。',
    removedShareOwner: 'さんがオーナーを削除しました。',
    attachedBoat: 'さんがボート「{name}」を紐づけました。',
  },
})

const KO = mergeStrings(EN, {
  someone: '누군가',
  sectionFallback: '업데이트',
  resourceSectionBody: '{actor}{action}',
  tripCompletedTitle: '{boatName}: 항해 완료',
  tripCompletedBody: '{tripTitle}이(가) 완료로 표시되었습니다.',
  adminJobCompletedTitle: '백그라운드 작업 완료',
  adminJobFailedTitle: '백그라운드 작업 실패',
  chatNewMessageTitle: '새 메시지',
  chatNewMessageBody: 'Logmaster에 새 메시지가 있습니다.',
  sectionByTopic: {
    BOAT_PHOTOS: '사진 업데이트',
    BOAT_DOCUMENTS: '문서 업데이트',
    BOAT_ASSETS: '자산 업데이트',
    BOAT_MEMBERS: '멤버 업데이트',
    BOAT_CONTACTS: '연락처 업데이트',
    BOAT_SHARES: '지분 업데이트',
    ORG_MEMBERS: '멤버 업데이트',
    ORG_DOCUMENTS: '문서 업데이트',
    ORG_CONTACTS: '연락처 업데이트',
    ORG_BOATS: '보트 업데이트',
  },
  actions: {
    uploadedPhoto: '님이 사진을 업로드했습니다.',
    updatedPhoto: '님이 사진을 수정했습니다.',
    deletedPhoto: '님이 사진을 삭제했습니다.',
    addedDocumentCategory: '님이 문서 카테고리를 추가했습니다.',
    uploadedDocument: '님이 문서를 업로드했습니다.',
    addedDocumentLink: '님이 문서 링크를 추가했습니다.',
    updatedDocument: '님이 문서를 수정했습니다.',
    deletedDocument: '님이 문서를 삭제했습니다.',
    addedAsset: '님이 자산 “{name}”을(를) 추가했습니다.',
    updatedAsset: '님이 자산 “{name}”을(를) 수정했습니다.',
    removedAsset: '님이 자산 “{name}”을(를) 제거했습니다.',
    loggedWorkOnAsset: '님이 자산 “{name}” 작업을 기록했습니다.',
    sentMemberInvite: '님이 멤버 초대를 보냈습니다.',
    addedMember: '님이 멤버를 추가했습니다.',
    createdMemberInviteLink: '님이 초대 링크를 만들었습니다.',
    changedMemberRole: '님이 멤버 역할을 변경했습니다.',
    removedMember: '님이 멤버를 제거했습니다.',
    joinedOrg: '님이 조직에 참여했습니다.',
    addedContact: '님이 연락처 “{name}”을(를) 추가했습니다.',
    updatedContact: '님이 연락처를 수정했습니다.',
    removedContact: '님이 연락처를 제거했습니다.',
    updatedShareStructure: '님이 지분 구조를 업데이트했습니다.',
    updatedShareLabel: '님이 지분 라벨을 업데이트했습니다.',
    assignedShareOwner: '님이 소유자를 지정했습니다.',
    removedShareOwner: '님이 소유자를 제거했습니다.',
    attachedBoat: '님이 보트 “{name}”을(를) 연결했습니다.',
  },
})

const ZH = mergeStrings(EN, {
  someone: '某人',
  sectionFallback: '更新',
  resourceSectionBody: '{actor} {action}',
  tripCompletedTitle: '{boatName}：行程已完成',
  tripCompletedBody: '{tripTitle} 已标记为完成。',
  adminJobCompletedTitle: '后台任务已完成',
  adminJobFailedTitle: '后台任务失败',
  chatNewMessageTitle: '新消息',
  chatNewMessageBody: '您在 Logmaster 中有新消息。',
  sectionByTopic: {
    BOAT_PHOTOS: '照片已更新',
    BOAT_DOCUMENTS: '文档已更新',
    BOAT_ASSETS: '资产已更新',
    BOAT_MEMBERS: '成员已更新',
    BOAT_CONTACTS: '联系人已更新',
    BOAT_SHARES: '份额已更新',
    ORG_MEMBERS: '成员已更新',
    ORG_DOCUMENTS: '文档已更新',
    ORG_CONTACTS: '联系人已更新',
    ORG_BOATS: '船舶已更新',
  },
  actions: {
    uploadedPhoto: '上传了照片。',
    updatedPhoto: '更新了照片。',
    deletedPhoto: '删除了照片。',
    addedDocumentCategory: '添加了文档分类。',
    uploadedDocument: '上传了文档。',
    addedDocumentLink: '添加了文档链接。',
    updatedDocument: '更新了文档。',
    deletedDocument: '删除了文档。',
    addedAsset: '添加了资产“{name}”。',
    updatedAsset: '更新了资产“{name}”。',
    removedAsset: '移除了资产“{name}”。',
    loggedWorkOnAsset: '记录了资产“{name}”的工作。',
    sentMemberInvite: '发送了成员邀请。',
    addedMember: '添加了成员。',
    createdMemberInviteLink: '创建了邀请链接。',
    changedMemberRole: '更改了成员角色。',
    removedMember: '移除了成员。',
    joinedOrg: '加入了组织。',
    addedContact: '添加了联系人“{name}”。',
    updatedContact: '更新了联系人。',
    removedContact: '移除了联系人。',
    updatedShareStructure: '更新了份额结构。',
    updatedShareLabel: '更新了份额标签。',
    assignedShareOwner: '指定了所有者。',
    removedShareOwner: '移除了所有者。',
    attachedBoat: '关联了船舶“{name}”。',
  },
})

const YUE = mergeStrings(EN, {
  someone: '某人',
  sectionFallback: '更新',
  resourceSectionBody: '{actor} {action}',
  tripCompletedTitle: '{boatName}：航程完成',
  tripCompletedBody: '{tripTitle} 已標記為完成。',
  adminJobCompletedTitle: '背景工作完成',
  adminJobFailedTitle: '背景工作失敗',
  chatNewMessageTitle: '新訊息',
  chatNewMessageBody: '你喺 Logmaster 有新訊息。',
  sectionByTopic: {
    BOAT_PHOTOS: '相片已更新',
    BOAT_DOCUMENTS: '文件已更新',
    BOAT_ASSETS: '資產已更新',
    BOAT_MEMBERS: '成員已更新',
    BOAT_CONTACTS: '聯絡人已更新',
    BOAT_SHARES: '份額已更新',
    ORG_MEMBERS: '成員已更新',
    ORG_DOCUMENTS: '文件已更新',
    ORG_CONTACTS: '聯絡人已更新',
    ORG_BOATS: '船隻已更新',
  },
  actions: {
    uploadedPhoto: '上載咗相片。',
    updatedPhoto: '更新咗相片。',
    deletedPhoto: '刪除咗相片。',
    addedDocumentCategory: '加咗文件分類。',
    uploadedDocument: '上載咗文件。',
    addedDocumentLink: '加咗文件連結。',
    updatedDocument: '更新咗文件。',
    deletedDocument: '刪除咗文件。',
    addedAsset: '加咗資產「{name}」。',
    updatedAsset: '更新咗資產「{name}」。',
    removedAsset: '移除咗資產「{name}」。',
    loggedWorkOnAsset: '記錄咗資產「{name}」嘅工作。',
    sentMemberInvite: '發送咗成員邀請。',
    addedMember: '加咗成員。',
    createdMemberInviteLink: '建立咗邀請連結。',
    changedMemberRole: '更改咗成員角色。',
    removedMember: '移除咗成員。',
    joinedOrg: '加入咗組織。',
    addedContact: '加咗聯絡人「{name}」。',
    updatedContact: '更新咗聯絡人。',
    removedContact: '移除咗聯絡人。',
    updatedShareStructure: '更新咗份額結構。',
    updatedShareLabel: '更新咗份額標籤。',
    assignedShareOwner: '指定咗擁有人。',
    removedShareOwner: '移除咗擁有人。',
    attachedBoat: '關聯咗船隻「{name}」。',
  },
})

const AR = mergeStrings(EN, {
  someone: 'شخص ما',
  sectionFallback: 'تحديثات',
  tripCompletedTitle: '{boatName}: اكتملت الرحلة',
  tripCompletedBody: 'تم وضع علامة اكتمال على {tripTitle}.',
  adminJobCompletedTitle: 'اكتملت مهمة الخلفية',
  adminJobFailedTitle: 'فشلت مهمة الخلفية',
  chatNewMessageTitle: 'رسالة جديدة',
  chatNewMessageBody: 'لديك رسالة جديدة في Logmaster.',
  sectionByTopic: {
    BOAT_PHOTOS: 'تم تحديث الصور',
    BOAT_DOCUMENTS: 'تم تحديث المستندات',
    BOAT_ASSETS: 'تم تحديث الأصول',
    BOAT_MEMBERS: 'تم تحديث الأعضاء',
    BOAT_CONTACTS: 'تم تحديث جهات الاتصال',
    BOAT_SHARES: 'تم تحديث الحصص',
    ORG_MEMBERS: 'تم تحديث الأعضاء',
    ORG_DOCUMENTS: 'تم تحديث المستندات',
    ORG_CONTACTS: 'تم تحديث جهات الاتصال',
    ORG_BOATS: 'تم تحديث القوارب',
  },
  actions: {
    uploadedPhoto: 'رفع صورة.',
    updatedPhoto: 'حدّث صورة.',
    deletedPhoto: 'حذف صورة.',
    addedDocumentCategory: 'أضاف فئة مستندات.',
    uploadedDocument: 'رفع مستندًا.',
    addedDocumentLink: 'أضاف رابط مستند.',
    updatedDocument: 'حدّث مستندًا.',
    deletedDocument: 'حذف مستندًا.',
    addedAsset: 'أضاف الأصل «{name}».',
    updatedAsset: 'حدّث الأصل «{name}».',
    removedAsset: 'أزال الأصل «{name}».',
    loggedWorkOnAsset: 'سجّل عملًا على «{name}».',
    sentMemberInvite: 'أرسل دعوة عضو.',
    addedMember: 'أضاف عضوًا.',
    createdMemberInviteLink: 'أنشأ رابط دعوة.',
    changedMemberRole: 'غيّر دور عضو.',
    removedMember: 'أزال عضوًا.',
    joinedOrg: 'انضم إلى المنظمة.',
    addedContact: 'أضاف جهة الاتصال «{name}».',
    updatedContact: 'حدّث جهة اتصال.',
    removedContact: 'أزال جهة اتصال.',
    updatedShareStructure: 'حدّث هيكل الحصص.',
    updatedShareLabel: 'حدّث تسمية حصة.',
    assignedShareOwner: 'عيّن مالكًا.',
    removedShareOwner: 'أزال مالكًا.',
    attachedBoat: 'ربط القارب «{name}».',
  },
})

const copyByLocale: Record<InviteLocale, ActivityNotificationStrings> = {
  en: EN,
  sv: SV,
  de: DE,
  fr: FR,
  es: ES,
  da: DA,
  nl: NL,
  pt: PT,
  fi: FI,
  el: EL,
  tr: TR,
  vi: VI,
  ja: JA,
  ko: KO,
  zh: ZH,
  yue: YUE,
  ar: AR,
}

for (const code of INVITE_LOCALE_CODES) {
  if (!copyByLocale[code]) copyByLocale[code] = EN
}

export function getActivityNotificationStrings(
  locale: InviteLocale,
): ActivityNotificationStrings {
  return copyByLocale[locale] ?? EN
}
