import { useEffect, useRef } from 'react'
import { toast } from 'sonner'
import {
  isBackgroundTrackerRunning,
  startBackgroundTracker,
  stopBackgroundTracker
  
} from '../lib/native/background-tracker'
import type {BackgroundPosition} from '../lib/native/background-tracker';
import { setLocationAccessEnabled } from '../lib/device-position'
import { supportsBackgroundGps } from '../lib/platform'
import { useAppOptionsStore } from '../stores/app-options'
import { useLogbookStore } from '../stores/logbook'
import { AUTO_GENERATED_ENTRY_NOTE } from '../domain/instrument-data'

const AUTO_TRACK_SOURCE = 'background-gps'

export function BackgroundTripRecorder() {
  const booted = useLogbookStore((state) => state.booted)
  const trips = useLogbookStore((state) => state.trips)
  const activeTripId = useLogbookStore((state) => state.activeTripId)
  const addEntry = useLogbookStore((state) => state.addEntry)
  const backgroundTripRecording = useAppOptionsStore(
    (state) => state.backgroundTripRecording,
  )
  const recordingTripId = useAppOptionsStore((state) => state.recordingTripId)
  const devTripReplay = useAppOptionsStore((state) => state.devTripReplay)
  const setRecordingTripId = useAppOptionsStore(
    (state) => state.setRecordingTripId,
  )
  const autoTrackIntervalMinutes = useAppOptionsStore(
    (state) => state.autoTrackIntervalMinutes,
  )
  const autoTrackMinDistanceMeters = useAppOptionsStore(
    (state) => state.autoTrackMinDistanceMeters,
  )
  const startingRef = useRef(false)

  useEffect(() => {
    if (!booted) return

    const recordingTrip = trips.find((trip) => trip.id === recordingTripId)
    if (!recordingTripId || recordingTrip?.status !== 'IN_PROGRESS') {
      if (recordingTripId) setRecordingTripId(null)
      setLocationAccessEnabled(false)
      return
    }

    setLocationAccessEnabled(true)
  }, [booted, recordingTripId, setRecordingTripId, trips])

  useEffect(() => {
    if (!supportsBackgroundGps()) return

    let cancelled = false

    async function syncTracker() {
      const shouldTrack = Boolean(
        activeTripId &&
          backgroundTripRecording &&
          recordingTripId === activeTripId &&
          devTripReplay?.targetTripId !== activeTripId,
      )

      if (!shouldTrack) {
        if (isBackgroundTrackerRunning()) {
          await stopBackgroundTracker()
        }
        return
      }

      if (isBackgroundTrackerRunning() || startingRef.current || !activeTripId) {
        return
      }

      startingRef.current = true
      try {
        const tripId = activeTripId
        await startBackgroundTracker({
          intervalMinutes: autoTrackIntervalMinutes,
          minDistanceMeters: autoTrackMinDistanceMeters,
          onPosition: async (position: BackgroundPosition) => {
            if (cancelled) return
            await addEntry({
              tripId,
              type: 'HOURLY_LOG',
              latitude: position.latitude,
              longitude: position.longitude,
              accuracy: position.accuracy,
              heading: position.heading,
              timestamp: position.timestamp,
              notes: AUTO_GENERATED_ENTRY_NOTE,
              data: {
                autoGenerated: true,
                source: AUTO_TRACK_SOURCE,
              },
            })
          },
          onError: (message: string) => {
            if (!cancelled) toast.error(message)
          },
        })
      } catch (error) {
        const message =
          error instanceof Error
            ? error.message
            : 'Could not start background trip recording.'
        toast.error(message)
      } finally {
        startingRef.current = false
      }
    }

    void syncTracker()

    return () => {
      cancelled = true
      void stopBackgroundTracker()
    }
  }, [
    activeTripId,
    addEntry,
    autoTrackIntervalMinutes,
    autoTrackMinDistanceMeters,
    backgroundTripRecording,
    devTripReplay?.targetTripId,
    recordingTripId,
  ])

  return null
}
