import { useEffect, useRef } from 'react'
import { toast } from 'sonner'
import {
  DEV_TRIP_REPLAY_ENTRY_NOTE,
  DEV_TRIP_REPLAY_SOURCE,
  hasReplayedSourceEntry,
  replayDetectionKind,
  replayDurationMs,
  replayEntryElapsedMs,
  replayPositionAt,
  replaySourceEntries,
  replayTimestamp,
} from '../lib/dev-trip-replay'
import { effectiveTimeTravelIso } from '../lib/dev-time-travel'
import {
  clearDevPositionOverride,
  setDevPositionOverride,
} from '../lib/device-position'
import { useAppOptionsStore } from '../stores/app-options'
import { useLogbookStore } from '../stores/logbook'

const REPLAY_TICK_MS = 1_000

export function DevTripReplayController() {
  const replay = useAppOptionsStore((state) => state.devTripReplay)
  const devMode = useAppOptionsStore((state) => state.devMode)
  const timeTravelEnabled = useAppOptionsStore(
    (state) => state.devTimeTravelEnabled,
  )
  const timeTravelValue = useAppOptionsStore(
    (state) => state.devLogEntryDraftTimeIso,
  )
  const timeTravelAnchor = useAppOptionsStore(
    (state) => state.devTimeTravelAnchorRealIso,
  )
  const booted = useLogbookStore((state) => state.booted)
  const trips = useLogbookStore((state) => state.trips)
  const entries = useLogbookStore((state) => state.entries)
  const processingRef = useRef(false)

  useEffect(() => {
    if (!booted || !devMode || !replay) return

    const sourceTrip = trips.find((trip) => trip.id === replay.sourceTripId)
    const targetTrip = trips.find((trip) => trip.id === replay.targetTripId)
    if (!sourceTrip || !targetTrip) {
      const options = useAppOptionsStore.getState()
      options.setDevTripReplay(null)
      if (options.recordingTripId === replay.targetTripId) {
        options.setRecordingTripId(null)
      }
      clearDevPositionOverride()
      toast.error('Trip replay stopped because one of its trips is unavailable.')
      return
    }

    if (targetTrip.status === 'COMPLETED') {
      const options = useAppOptionsStore.getState()
      options.setDevTripReplay(null)
      if (options.recordingTripId === targetTrip.id) {
        options.setRecordingTripId(null)
      }
      clearDevPositionOverride()
      return
    }

    const sourceEntries = entries.filter(
      (entry) => entry.tripId === sourceTrip.id && !entry.deleted,
    )
    const targetEntries = entries.filter(
      (entry) => entry.tripId === targetTrip.id,
    )

    const tick = async () => {
      if (processingRef.current) return
      processingRef.current = true
      try {
        const realNowMs = Date.now()
        const virtualNowMs =
          timeTravelEnabled && timeTravelValue
            ? Date.parse(
                effectiveTimeTravelIso(
                  timeTravelValue,
                  timeTravelAnchor,
                  realNowMs,
                ),
              )
            : Date.parse(replay.targetStartedAt) +
              (realNowMs - Date.parse(replay.realStartedAt))
        const elapsedMs = Math.max(
          0,
          virtualNowMs - Date.parse(replay.targetStartedAt),
        )
        const currentPosition = replayPositionAt(
          sourceTrip,
          sourceEntries,
          elapsedMs,
        )
        if (currentPosition) setDevPositionOverride(currentPosition)

        const processed = new Set(
          targetEntries
            .map((entry) => entry.data?.replaySourceEntryId)
            .filter((id): id is string => typeof id === 'string'),
        )
        const dueEntries = replaySourceEntries(sourceEntries, sourceTrip.id).filter(
          (entry) =>
            entry.type !== 'START_TRIP' &&
            replayEntryElapsedMs(entry, sourceTrip.startedAt) <= elapsedMs &&
            !processed.has(entry.id) &&
            !hasReplayedSourceEntry(targetEntries, entry.id),
        )

        for (const sourceEntry of dueEntries) {
          const eventElapsedMs = replayEntryElapsedMs(
            sourceEntry,
            sourceTrip.startedAt,
          )
          const eventPosition = replayPositionAt(
            sourceTrip,
            sourceEntries,
            eventElapsedMs,
          )
          if (eventPosition) setDevPositionOverride(eventPosition)
          await useLogbookStore.getState().addEntry({
            tripId: targetTrip.id,
            type: sourceEntry.type,
            timestamp: replayTimestamp(replay.targetStartedAt, eventElapsedMs),
            latitude: eventPosition?.latitude,
            longitude: eventPosition?.longitude,
            accuracy: eventPosition?.accuracy,
            heading: eventPosition?.heading,
            notes: DEV_TRIP_REPLAY_ENTRY_NOTE,
            data: {
              autoGenerated: true,
              source: DEV_TRIP_REPLAY_SOURCE,
              detection: replayDetectionKind(sourceEntry.type),
              replaySourceTripId: sourceTrip.id,
              replaySourceEntryId: sourceEntry.id,
            },
          })
          processed.add(sourceEntry.id)
        }

        const durationMs = replayDurationMs(sourceTrip, sourceEntries)
        const currentTarget = useLogbookStore
          .getState()
          .trips.find((trip) => trip.id === targetTrip.id)
        if (elapsedMs >= durationMs && currentTarget?.status !== 'COMPLETED') {
          const endPosition = replayPositionAt(
            sourceTrip,
            sourceEntries,
            durationMs,
          )
          const completionSourceId = `completion:${sourceTrip.id}`
          if (
            !hasReplayedSourceEntry(
              useLogbookStore
                .getState()
                .entries.filter((entry) => entry.tripId === targetTrip.id),
              completionSourceId,
            )
          ) {
            await useLogbookStore.getState().addEntry({
              tripId: targetTrip.id,
              type: 'END_TRIP',
              timestamp: replayTimestamp(replay.targetStartedAt, durationMs),
              latitude: endPosition?.latitude,
              longitude: endPosition?.longitude,
              accuracy: endPosition?.accuracy,
              heading: endPosition?.heading,
              notes: DEV_TRIP_REPLAY_ENTRY_NOTE,
              data: {
                autoGenerated: true,
                source: DEV_TRIP_REPLAY_SOURCE,
                detection: 'instrument',
                replaySourceTripId: sourceTrip.id,
                replaySourceEntryId: completionSourceId,
              },
            })
          }
        }

        const finished =
          useLogbookStore
            .getState()
            .trips.find((trip) => trip.id === targetTrip.id)?.status ===
          'COMPLETED'
        if (finished) {
          const options = useAppOptionsStore.getState()
          options.setDevTripReplay(null)
          if (options.recordingTripId === targetTrip.id) {
            options.setRecordingTripId(null)
          }
          clearDevPositionOverride()
          toast.success('Trip replay completed')
        } else if (currentPosition) {
          setDevPositionOverride(currentPosition)
        }
      } catch (error) {
        toast.error(
          error instanceof Error ? error.message : 'Trip replay failed.',
        )
      } finally {
        processingRef.current = false
      }
    }

    void tick()
    const intervalId = window.setInterval(() => void tick(), REPLAY_TICK_MS)
    return () => window.clearInterval(intervalId)
  }, [
    booted,
    devMode,
    entries,
    replay,
    timeTravelAnchor,
    timeTravelEnabled,
    timeTravelValue,
    trips,
  ])

  return null
}
