/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as MainTermsRouteImport } from './routes/_main/terms'
import { Route as MainSignInRouteImport } from './routes/_main/sign-in'
import { Route as MainPrivacyRouteImport } from './routes/_main/privacy'
import { Route as MainMapRouteImport } from './routes/_main/map'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainTripsIndexRouteImport } from './routes/_main/trips/index'
import { Route as MainRoutesIndexRouteImport } from './routes/_main/routes/index'
import { Route as MainResetPasswordIndexRouteImport } from './routes/_main/reset-password/index'
import { Route as MainCrewIndexRouteImport } from './routes/_main/crew/index'
import { Route as MainBoatsIndexRouteImport } from './routes/_main/boats/index'
import { Route as MainAdminIndexRouteImport } from './routes/_main/admin/index'
import { Route as MainTripsTripIdRouteImport } from './routes/_main/trips/$tripId'
import { Route as MainRoutesRouteIdRouteImport } from './routes/_main/routes/$routeId'
import { Route as MainResetPasswordTokenRouteImport } from './routes/_main/reset-password/$token'
import { Route as MainPlacesPhotosRouteImport } from './routes/_main/places/photos'
import { Route as MainDevTimeTravelRouteImport } from './routes/_main/dev/time-travel'
import { Route as MainBoatsNewRouteImport } from './routes/_main/boats/new'
import { Route as MainBoatsBoatIdRouteImport } from './routes/_main/boats/$boatId'
import { Route as MainAdminUsersRouteImport } from './routes/_main/admin/users'
import { Route as MainAdminTripsRouteImport } from './routes/_main/admin/trips'
import { Route as MainAdminPgbossRouteImport } from './routes/_main/admin/pgboss'
import { Route as MainAdminJobManagementRouteImport } from './routes/_main/admin/job-management'
import { Route as MainAdminCountriesRouteImport } from './routes/_main/admin/countries'
import { Route as MainAdminRegionsIndexRouteImport } from './routes/_main/admin/regions/index'
import { Route as MainAdminJobsIndexRouteImport } from './routes/_main/admin/jobs/index'
import { Route as MainCrewInviteTokenRouteImport } from './routes/_main/crew/invite/$token'
import { Route as MainAdminJobsSystemRouteImport } from './routes/_main/admin/jobs/system'
import { Route as MainAdminJobsMarinasRouteImport } from './routes/_main/admin/jobs/marinas'
import { Route as MainAdminJobsGeoFeaturesRouteImport } from './routes/_main/admin/jobs/geo-features'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTermsRoute = MainTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSignInRoute = MainSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPrivacyRoute = MainPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMapRoute = MainMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTripsIndexRoute = MainTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRoutesIndexRoute = MainRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainResetPasswordIndexRoute = MainResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCrewIndexRoute = MainCrewIndexRouteImport.update({
  id: '/crew/',
  path: '/crew/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBoatsIndexRoute = MainBoatsIndexRouteImport.update({
  id: '/boats/',
  path: '/boats/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminIndexRoute = MainAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTripsTripIdRoute = MainTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRoutesRouteIdRoute = MainRoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainResetPasswordTokenRoute = MainResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPlacesPhotosRoute = MainPlacesPhotosRouteImport.update({
  id: '/places/photos',
  path: '/places/photos',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDevTimeTravelRoute = MainDevTimeTravelRouteImport.update({
  id: '/dev/time-travel',
  path: '/dev/time-travel',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBoatsNewRoute = MainBoatsNewRouteImport.update({
  id: '/boats/new',
  path: '/boats/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBoatsBoatIdRoute = MainBoatsBoatIdRouteImport.update({
  id: '/boats/$boatId',
  path: '/boats/$boatId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminUsersRoute = MainAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminTripsRoute = MainAdminTripsRouteImport.update({
  id: '/admin/trips',
  path: '/admin/trips',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminPgbossRoute = MainAdminPgbossRouteImport.update({
  id: '/admin/pgboss',
  path: '/admin/pgboss',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminJobManagementRoute = MainAdminJobManagementRouteImport.update({
  id: '/admin/job-management',
  path: '/admin/job-management',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminCountriesRoute = MainAdminCountriesRouteImport.update({
  id: '/admin/countries',
  path: '/admin/countries',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminRegionsIndexRoute = MainAdminRegionsIndexRouteImport.update({
  id: '/admin/regions/',
  path: '/admin/regions/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminJobsIndexRoute = MainAdminJobsIndexRouteImport.update({
  id: '/admin/jobs/',
  path: '/admin/jobs/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCrewInviteTokenRoute = MainCrewInviteTokenRouteImport.update({
  id: '/crew/invite/$token',
  path: '/crew/invite/$token',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminJobsSystemRoute = MainAdminJobsSystemRouteImport.update({
  id: '/admin/jobs/system',
  path: '/admin/jobs/system',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminJobsMarinasRoute = MainAdminJobsMarinasRouteImport.update({
  id: '/admin/jobs/marinas',
  path: '/admin/jobs/marinas',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminJobsGeoFeaturesRoute =
  MainAdminJobsGeoFeaturesRouteImport.update({
    id: '/admin/jobs/geo-features',
    path: '/admin/jobs/geo-features',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/about': typeof MainAboutRoute
  '/map': typeof MainMapRoute
  '/privacy': typeof MainPrivacyRoute
  '/sign-in': typeof MainSignInRoute
  '/terms': typeof MainTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/countries': typeof MainAdminCountriesRoute
  '/admin/job-management': typeof MainAdminJobManagementRoute
  '/admin/pgboss': typeof MainAdminPgbossRoute
  '/admin/trips': typeof MainAdminTripsRoute
  '/admin/users': typeof MainAdminUsersRoute
  '/boats/$boatId': typeof MainBoatsBoatIdRoute
  '/boats/new': typeof MainBoatsNewRoute
  '/dev/time-travel': typeof MainDevTimeTravelRoute
  '/places/photos': typeof MainPlacesPhotosRoute
  '/reset-password/$token': typeof MainResetPasswordTokenRoute
  '/routes/$routeId': typeof MainRoutesRouteIdRoute
  '/trips/$tripId': typeof MainTripsTripIdRoute
  '/admin/': typeof MainAdminIndexRoute
  '/boats/': typeof MainBoatsIndexRoute
  '/crew/': typeof MainCrewIndexRoute
  '/reset-password/': typeof MainResetPasswordIndexRoute
  '/routes/': typeof MainRoutesIndexRoute
  '/trips/': typeof MainTripsIndexRoute
  '/admin/jobs/geo-features': typeof MainAdminJobsGeoFeaturesRoute
  '/admin/jobs/marinas': typeof MainAdminJobsMarinasRoute
  '/admin/jobs/system': typeof MainAdminJobsSystemRoute
  '/crew/invite/$token': typeof MainCrewInviteTokenRoute
  '/admin/jobs/': typeof MainAdminJobsIndexRoute
  '/admin/regions/': typeof MainAdminRegionsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/map': typeof MainMapRoute
  '/privacy': typeof MainPrivacyRoute
  '/sign-in': typeof MainSignInRoute
  '/terms': typeof MainTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof MainIndexRoute
  '/admin/countries': typeof MainAdminCountriesRoute
  '/admin/job-management': typeof MainAdminJobManagementRoute
  '/admin/pgboss': typeof MainAdminPgbossRoute
  '/admin/trips': typeof MainAdminTripsRoute
  '/admin/users': typeof MainAdminUsersRoute
  '/boats/$boatId': typeof MainBoatsBoatIdRoute
  '/boats/new': typeof MainBoatsNewRoute
  '/dev/time-travel': typeof MainDevTimeTravelRoute
  '/places/photos': typeof MainPlacesPhotosRoute
  '/reset-password/$token': typeof MainResetPasswordTokenRoute
  '/routes/$routeId': typeof MainRoutesRouteIdRoute
  '/trips/$tripId': typeof MainTripsTripIdRoute
  '/admin': typeof MainAdminIndexRoute
  '/boats': typeof MainBoatsIndexRoute
  '/crew': typeof MainCrewIndexRoute
  '/reset-password': typeof MainResetPasswordIndexRoute
  '/routes': typeof MainRoutesIndexRoute
  '/trips': typeof MainTripsIndexRoute
  '/admin/jobs/geo-features': typeof MainAdminJobsGeoFeaturesRoute
  '/admin/jobs/marinas': typeof MainAdminJobsMarinasRoute
  '/admin/jobs/system': typeof MainAdminJobsSystemRoute
  '/crew/invite/$token': typeof MainCrewInviteTokenRoute
  '/admin/jobs': typeof MainAdminJobsIndexRoute
  '/admin/regions': typeof MainAdminRegionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/map': typeof MainMapRoute
  '/_main/privacy': typeof MainPrivacyRoute
  '/_main/sign-in': typeof MainSignInRoute
  '/_main/terms': typeof MainTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/_main/': typeof MainIndexRoute
  '/_main/admin/countries': typeof MainAdminCountriesRoute
  '/_main/admin/job-management': typeof MainAdminJobManagementRoute
  '/_main/admin/pgboss': typeof MainAdminPgbossRoute
  '/_main/admin/trips': typeof MainAdminTripsRoute
  '/_main/admin/users': typeof MainAdminUsersRoute
  '/_main/boats/$boatId': typeof MainBoatsBoatIdRoute
  '/_main/boats/new': typeof MainBoatsNewRoute
  '/_main/dev/time-travel': typeof MainDevTimeTravelRoute
  '/_main/places/photos': typeof MainPlacesPhotosRoute
  '/_main/reset-password/$token': typeof MainResetPasswordTokenRoute
  '/_main/routes/$routeId': typeof MainRoutesRouteIdRoute
  '/_main/trips/$tripId': typeof MainTripsTripIdRoute
  '/_main/admin/': typeof MainAdminIndexRoute
  '/_main/boats/': typeof MainBoatsIndexRoute
  '/_main/crew/': typeof MainCrewIndexRoute
  '/_main/reset-password/': typeof MainResetPasswordIndexRoute
  '/_main/routes/': typeof MainRoutesIndexRoute
  '/_main/trips/': typeof MainTripsIndexRoute
  '/_main/admin/jobs/geo-features': typeof MainAdminJobsGeoFeaturesRoute
  '/_main/admin/jobs/marinas': typeof MainAdminJobsMarinasRoute
  '/_main/admin/jobs/system': typeof MainAdminJobsSystemRoute
  '/_main/crew/invite/$token': typeof MainCrewInviteTokenRoute
  '/_main/admin/jobs/': typeof MainAdminJobsIndexRoute
  '/_main/admin/regions/': typeof MainAdminRegionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/map'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/api/$'
    | '/admin/countries'
    | '/admin/job-management'
    | '/admin/pgboss'
    | '/admin/trips'
    | '/admin/users'
    | '/boats/$boatId'
    | '/boats/new'
    | '/dev/time-travel'
    | '/places/photos'
    | '/reset-password/$token'
    | '/routes/$routeId'
    | '/trips/$tripId'
    | '/admin/'
    | '/boats/'
    | '/crew/'
    | '/reset-password/'
    | '/routes/'
    | '/trips/'
    | '/admin/jobs/geo-features'
    | '/admin/jobs/marinas'
    | '/admin/jobs/system'
    | '/crew/invite/$token'
    | '/admin/jobs/'
    | '/admin/regions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/map'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/api/$'
    | '/'
    | '/admin/countries'
    | '/admin/job-management'
    | '/admin/pgboss'
    | '/admin/trips'
    | '/admin/users'
    | '/boats/$boatId'
    | '/boats/new'
    | '/dev/time-travel'
    | '/places/photos'
    | '/reset-password/$token'
    | '/routes/$routeId'
    | '/trips/$tripId'
    | '/admin'
    | '/boats'
    | '/crew'
    | '/reset-password'
    | '/routes'
    | '/trips'
    | '/admin/jobs/geo-features'
    | '/admin/jobs/marinas'
    | '/admin/jobs/system'
    | '/crew/invite/$token'
    | '/admin/jobs'
    | '/admin/regions'
  id:
    | '__root__'
    | '/_main'
    | '/_main/about'
    | '/_main/map'
    | '/_main/privacy'
    | '/_main/sign-in'
    | '/_main/terms'
    | '/api/$'
    | '/_main/'
    | '/_main/admin/countries'
    | '/_main/admin/job-management'
    | '/_main/admin/pgboss'
    | '/_main/admin/trips'
    | '/_main/admin/users'
    | '/_main/boats/$boatId'
    | '/_main/boats/new'
    | '/_main/dev/time-travel'
    | '/_main/places/photos'
    | '/_main/reset-password/$token'
    | '/_main/routes/$routeId'
    | '/_main/trips/$tripId'
    | '/_main/admin/'
    | '/_main/boats/'
    | '/_main/crew/'
    | '/_main/reset-password/'
    | '/_main/routes/'
    | '/_main/trips/'
    | '/_main/admin/jobs/geo-features'
    | '/_main/admin/jobs/marinas'
    | '/_main/admin/jobs/system'
    | '/_main/crew/invite/$token'
    | '/_main/admin/jobs/'
    | '/_main/admin/regions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/terms': {
      id: '/_main/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainTermsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/sign-in': {
      id: '/_main/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof MainSignInRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/privacy': {
      id: '/_main/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainPrivacyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/map': {
      id: '/_main/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MainMapRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/trips/': {
      id: '/_main/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof MainTripsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/routes/': {
      id: '/_main/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof MainRoutesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reset-password/': {
      id: '/_main/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof MainResetPasswordIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/crew/': {
      id: '/_main/crew/'
      path: '/crew'
      fullPath: '/crew/'
      preLoaderRoute: typeof MainCrewIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/boats/': {
      id: '/_main/boats/'
      path: '/boats'
      fullPath: '/boats/'
      preLoaderRoute: typeof MainBoatsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/': {
      id: '/_main/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/trips/$tripId': {
      id: '/_main/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof MainTripsTripIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/routes/$routeId': {
      id: '/_main/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof MainRoutesRouteIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reset-password/$token': {
      id: '/_main/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof MainResetPasswordTokenRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/places/photos': {
      id: '/_main/places/photos'
      path: '/places/photos'
      fullPath: '/places/photos'
      preLoaderRoute: typeof MainPlacesPhotosRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/dev/time-travel': {
      id: '/_main/dev/time-travel'
      path: '/dev/time-travel'
      fullPath: '/dev/time-travel'
      preLoaderRoute: typeof MainDevTimeTravelRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/boats/new': {
      id: '/_main/boats/new'
      path: '/boats/new'
      fullPath: '/boats/new'
      preLoaderRoute: typeof MainBoatsNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/boats/$boatId': {
      id: '/_main/boats/$boatId'
      path: '/boats/$boatId'
      fullPath: '/boats/$boatId'
      preLoaderRoute: typeof MainBoatsBoatIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/users': {
      id: '/_main/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof MainAdminUsersRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/trips': {
      id: '/_main/admin/trips'
      path: '/admin/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof MainAdminTripsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/pgboss': {
      id: '/_main/admin/pgboss'
      path: '/admin/pgboss'
      fullPath: '/admin/pgboss'
      preLoaderRoute: typeof MainAdminPgbossRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/job-management': {
      id: '/_main/admin/job-management'
      path: '/admin/job-management'
      fullPath: '/admin/job-management'
      preLoaderRoute: typeof MainAdminJobManagementRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/countries': {
      id: '/_main/admin/countries'
      path: '/admin/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof MainAdminCountriesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/regions/': {
      id: '/_main/admin/regions/'
      path: '/admin/regions'
      fullPath: '/admin/regions/'
      preLoaderRoute: typeof MainAdminRegionsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/jobs/': {
      id: '/_main/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof MainAdminJobsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/crew/invite/$token': {
      id: '/_main/crew/invite/$token'
      path: '/crew/invite/$token'
      fullPath: '/crew/invite/$token'
      preLoaderRoute: typeof MainCrewInviteTokenRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/jobs/system': {
      id: '/_main/admin/jobs/system'
      path: '/admin/jobs/system'
      fullPath: '/admin/jobs/system'
      preLoaderRoute: typeof MainAdminJobsSystemRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/jobs/marinas': {
      id: '/_main/admin/jobs/marinas'
      path: '/admin/jobs/marinas'
      fullPath: '/admin/jobs/marinas'
      preLoaderRoute: typeof MainAdminJobsMarinasRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/jobs/geo-features': {
      id: '/_main/admin/jobs/geo-features'
      path: '/admin/jobs/geo-features'
      fullPath: '/admin/jobs/geo-features'
      preLoaderRoute: typeof MainAdminJobsGeoFeaturesRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainMapRoute: typeof MainMapRoute
  MainPrivacyRoute: typeof MainPrivacyRoute
  MainSignInRoute: typeof MainSignInRoute
  MainTermsRoute: typeof MainTermsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainAdminCountriesRoute: typeof MainAdminCountriesRoute
  MainAdminJobManagementRoute: typeof MainAdminJobManagementRoute
  MainAdminPgbossRoute: typeof MainAdminPgbossRoute
  MainAdminTripsRoute: typeof MainAdminTripsRoute
  MainAdminUsersRoute: typeof MainAdminUsersRoute
  MainBoatsBoatIdRoute: typeof MainBoatsBoatIdRoute
  MainBoatsNewRoute: typeof MainBoatsNewRoute
  MainDevTimeTravelRoute: typeof MainDevTimeTravelRoute
  MainPlacesPhotosRoute: typeof MainPlacesPhotosRoute
  MainResetPasswordTokenRoute: typeof MainResetPasswordTokenRoute
  MainRoutesRouteIdRoute: typeof MainRoutesRouteIdRoute
  MainTripsTripIdRoute: typeof MainTripsTripIdRoute
  MainAdminIndexRoute: typeof MainAdminIndexRoute
  MainBoatsIndexRoute: typeof MainBoatsIndexRoute
  MainCrewIndexRoute: typeof MainCrewIndexRoute
  MainResetPasswordIndexRoute: typeof MainResetPasswordIndexRoute
  MainRoutesIndexRoute: typeof MainRoutesIndexRoute
  MainTripsIndexRoute: typeof MainTripsIndexRoute
  MainAdminJobsGeoFeaturesRoute: typeof MainAdminJobsGeoFeaturesRoute
  MainAdminJobsMarinasRoute: typeof MainAdminJobsMarinasRoute
  MainAdminJobsSystemRoute: typeof MainAdminJobsSystemRoute
  MainCrewInviteTokenRoute: typeof MainCrewInviteTokenRoute
  MainAdminJobsIndexRoute: typeof MainAdminJobsIndexRoute
  MainAdminRegionsIndexRoute: typeof MainAdminRegionsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainMapRoute: MainMapRoute,
  MainPrivacyRoute: MainPrivacyRoute,
  MainSignInRoute: MainSignInRoute,
  MainTermsRoute: MainTermsRoute,
  MainIndexRoute: MainIndexRoute,
  MainAdminCountriesRoute: MainAdminCountriesRoute,
  MainAdminJobManagementRoute: MainAdminJobManagementRoute,
  MainAdminPgbossRoute: MainAdminPgbossRoute,
  MainAdminTripsRoute: MainAdminTripsRoute,
  MainAdminUsersRoute: MainAdminUsersRoute,
  MainBoatsBoatIdRoute: MainBoatsBoatIdRoute,
  MainBoatsNewRoute: MainBoatsNewRoute,
  MainDevTimeTravelRoute: MainDevTimeTravelRoute,
  MainPlacesPhotosRoute: MainPlacesPhotosRoute,
  MainResetPasswordTokenRoute: MainResetPasswordTokenRoute,
  MainRoutesRouteIdRoute: MainRoutesRouteIdRoute,
  MainTripsTripIdRoute: MainTripsTripIdRoute,
  MainAdminIndexRoute: MainAdminIndexRoute,
  MainBoatsIndexRoute: MainBoatsIndexRoute,
  MainCrewIndexRoute: MainCrewIndexRoute,
  MainResetPasswordIndexRoute: MainResetPasswordIndexRoute,
  MainRoutesIndexRoute: MainRoutesIndexRoute,
  MainTripsIndexRoute: MainTripsIndexRoute,
  MainAdminJobsGeoFeaturesRoute: MainAdminJobsGeoFeaturesRoute,
  MainAdminJobsMarinasRoute: MainAdminJobsMarinasRoute,
  MainAdminJobsSystemRoute: MainAdminJobsSystemRoute,
  MainCrewInviteTokenRoute: MainCrewInviteTokenRoute,
  MainAdminJobsIndexRoute: MainAdminJobsIndexRoute,
  MainAdminRegionsIndexRoute: MainAdminRegionsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
