/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as MainSignInRouteImport } from './routes/_main/sign-in'
import { Route as MainResetPasswordRouteImport } from './routes/_main/reset-password'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainBoatsIndexRouteImport } from './routes/_main/boats/index'
import { Route as MainAdminIndexRouteImport } from './routes/_main/admin/index'
import { Route as MainBoatsNewRouteImport } from './routes/_main/boats/new'
import { Route as MainBoatsBoatIdRouteImport } from './routes/_main/boats/$boatId'
import { Route as MainAdminPgbossRouteImport } from './routes/_main/admin/pgboss'
import { Route as MainAdminCountriesRouteImport } from './routes/_main/admin/countries'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSignInRoute = MainSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainResetPasswordRoute = MainResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBoatsIndexRoute = MainBoatsIndexRouteImport.update({
  id: '/boats/',
  path: '/boats/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminIndexRoute = MainAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBoatsNewRoute = MainBoatsNewRouteImport.update({
  id: '/boats/new',
  path: '/boats/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBoatsBoatIdRoute = MainBoatsBoatIdRouteImport.update({
  id: '/boats/$boatId',
  path: '/boats/$boatId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminPgbossRoute = MainAdminPgbossRouteImport.update({
  id: '/admin/pgboss',
  path: '/admin/pgboss',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminCountriesRoute = MainAdminCountriesRouteImport.update({
  id: '/admin/countries',
  path: '/admin/countries',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/about': typeof MainAboutRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/sign-in': typeof MainSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/countries': typeof MainAdminCountriesRoute
  '/admin/pgboss': typeof MainAdminPgbossRoute
  '/boats/$boatId': typeof MainBoatsBoatIdRoute
  '/boats/new': typeof MainBoatsNewRoute
  '/admin/': typeof MainAdminIndexRoute
  '/boats/': typeof MainBoatsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/sign-in': typeof MainSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof MainIndexRoute
  '/admin/countries': typeof MainAdminCountriesRoute
  '/admin/pgboss': typeof MainAdminPgbossRoute
  '/boats/$boatId': typeof MainBoatsBoatIdRoute
  '/boats/new': typeof MainBoatsNewRoute
  '/admin': typeof MainAdminIndexRoute
  '/boats': typeof MainBoatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/reset-password': typeof MainResetPasswordRoute
  '/_main/sign-in': typeof MainSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/_main/': typeof MainIndexRoute
  '/_main/admin/countries': typeof MainAdminCountriesRoute
  '/_main/admin/pgboss': typeof MainAdminPgbossRoute
  '/_main/boats/$boatId': typeof MainBoatsBoatIdRoute
  '/_main/boats/new': typeof MainBoatsNewRoute
  '/_main/admin/': typeof MainAdminIndexRoute
  '/_main/boats/': typeof MainBoatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/reset-password'
    | '/sign-in'
    | '/api/$'
    | '/admin/countries'
    | '/admin/pgboss'
    | '/boats/$boatId'
    | '/boats/new'
    | '/admin/'
    | '/boats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/reset-password'
    | '/sign-in'
    | '/api/$'
    | '/'
    | '/admin/countries'
    | '/admin/pgboss'
    | '/boats/$boatId'
    | '/boats/new'
    | '/admin'
    | '/boats'
  id:
    | '__root__'
    | '/_main'
    | '/_main/about'
    | '/_main/reset-password'
    | '/_main/sign-in'
    | '/api/$'
    | '/_main/'
    | '/_main/admin/countries'
    | '/_main/admin/pgboss'
    | '/_main/boats/$boatId'
    | '/_main/boats/new'
    | '/_main/admin/'
    | '/_main/boats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/sign-in': {
      id: '/_main/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof MainSignInRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reset-password': {
      id: '/_main/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainResetPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/boats/': {
      id: '/_main/boats/'
      path: '/boats'
      fullPath: '/boats/'
      preLoaderRoute: typeof MainBoatsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/': {
      id: '/_main/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/boats/new': {
      id: '/_main/boats/new'
      path: '/boats/new'
      fullPath: '/boats/new'
      preLoaderRoute: typeof MainBoatsNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/boats/$boatId': {
      id: '/_main/boats/$boatId'
      path: '/boats/$boatId'
      fullPath: '/boats/$boatId'
      preLoaderRoute: typeof MainBoatsBoatIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/pgboss': {
      id: '/_main/admin/pgboss'
      path: '/admin/pgboss'
      fullPath: '/admin/pgboss'
      preLoaderRoute: typeof MainAdminPgbossRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/countries': {
      id: '/_main/admin/countries'
      path: '/admin/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof MainAdminCountriesRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainResetPasswordRoute: typeof MainResetPasswordRoute
  MainSignInRoute: typeof MainSignInRoute
  MainIndexRoute: typeof MainIndexRoute
  MainAdminCountriesRoute: typeof MainAdminCountriesRoute
  MainAdminPgbossRoute: typeof MainAdminPgbossRoute
  MainBoatsBoatIdRoute: typeof MainBoatsBoatIdRoute
  MainBoatsNewRoute: typeof MainBoatsNewRoute
  MainAdminIndexRoute: typeof MainAdminIndexRoute
  MainBoatsIndexRoute: typeof MainBoatsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainResetPasswordRoute: MainResetPasswordRoute,
  MainSignInRoute: MainSignInRoute,
  MainIndexRoute: MainIndexRoute,
  MainAdminCountriesRoute: MainAdminCountriesRoute,
  MainAdminPgbossRoute: MainAdminPgbossRoute,
  MainBoatsBoatIdRoute: MainBoatsBoatIdRoute,
  MainBoatsNewRoute: MainBoatsNewRoute,
  MainAdminIndexRoute: MainAdminIndexRoute,
  MainBoatsIndexRoute: MainBoatsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
